import json
from datetime import datetime

months=["Jan.","Feb.","Mar.","Apr.","May","Jun.","Jul.","Aug.","Sep.","Oct.","Nov.","Dec."]
birth_date=datetime(1946,6,14)

def format_date(date_str:str)->str:
    d=datetime.strptime(date_str,"%Y-%m-%d")
    return f"{months[d.month-1]} {d.day}, {d.year}"

def calc_age(date_str:str)->int:
    d=datetime.strptime(date_str,"%Y-%m-%d")
    a=d.year-birth_date.year
    if (d.month,d.day)<(birth_date.month,birth_date.day): a-=1
    return a

def sql_escape(v:str)->str: return v.replace("'","''")
def json_sql(o)->str: return "'"+json.dumps(o,separators=(",",":"),ensure_ascii=True).replace("'","''")+"'::jsonb"
def arr_sql(items)->str:
    if not items: return "ARRAY[]::text[]"
    return "ARRAY["+",".join("'"+sql_escape(x)+"'" for x in items)+"]::text[]"

def make_scores(date_start,category,subcategory,danger,lawlessness,impact_scope,authoritarianism,insanity,absurdity,credibility_risk,recency_intensity,rationale_short):
    return {
        "danger":danger,"insanity":insanity,"absurdity":absurdity,"lawlessness":lawlessness,"impact_scope":impact_scope,
        "rationale_short":rationale_short,"authoritarianism":authoritarianism,"credibility_risk":credibility_risk,
        "rationale_detail":f"{category}: {subcategory}. On {format_date(date_start)}, {rationale_short}","recency_intensity":recency_intensity,
    }

metrics={
    "war":{"impressions":196000000,"reach_estimate":684000000,"financial_cost_usd":1120000000,"public_reaction":{"negative":80,"neutral":14,"positive":6}},
    "diplomacy":{"impressions":168000000,"reach_estimate":571000000,"financial_cost_usd":510000000,"public_reaction":{"negative":76,"neutral":17,"positive":7}},
    "governance":{"impressions":155000000,"reach_estimate":529000000,"financial_cost_usd":310000000,"public_reaction":{"negative":77,"neutral":16,"positive":7}},
}

entries=[
{ "entry_number":1321,"title":"Trump Threatened Trade Retaliation Against Spain Over Refusal to Support Iran War Logistics","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP reported Trump threatened to cut trade ties with Spain after Madrid resisted U.S. use of joint bases for Iran strikes without U.N. cover. The move turned a military coalition dispute into economic coercion, reinforcing Trump's pattern of using tariffs and embargo threats as political punishment. It also widened fractures inside the Western alliance while conflict conditions were still volatile.","rationale":"AP reported Trump using trade threats to pressure Spain on Iran-war cooperation.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["Spain threat","trade retaliation","base access","Iran war","economic pressure"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/43e0f13e7b1c7e6ebcc4b558474aacdc","source_title":"Trump threatens trade cutoff with Spain over Iran-war base dispute","source_publisher":"AP News","scores":make_scores("2026-03-03","Foreign Policy","Diplomatic Breakdown",8,6,8,6,3,3,7,10,"Trump threatened economic retaliation against an ally over Iran-war cooperation.")},
{ "entry_number":1322,"title":"Trump Tied Spain Punishment to NATO Spending Complaints During Active War","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"In AP's account, Trump fused two pressure tracks at once: Iran-war support and long-running NATO spending grievances. By linking unrelated bargaining points in wartime, Trump increased transaction costs for allies and reduced policy clarity. The style fit his coercive negotiation brand, but it introduced additional instability during a regional military crisis.","rationale":"AP showed Trump combining NATO and Iran disputes into one coercive pressure package.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["NATO spending","Spain dispute","coercive package","alliance pressure","wartime bargaining"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/43e0f13e7b1c7e6ebcc4b558474aacdc","source_title":"Trump threatens trade cutoff with Spain over Iran-war base dispute","source_publisher":"AP News","scores":make_scores("2026-03-03","Foreign Policy","Diplomatic Breakdown",8,6,8,6,3,3,7,10,"Trump merged NATO burden-sharing complaints with Iran-war coercive demands.")},
{ "entry_number":1323,"title":"Trump's Spain Ultimatum Triggered EU Pushback on Who Controls Trade Policy","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP reported Spain's response emphasized that EU institutions, not bilateral White House pressure, govern trade frameworks. Trump's threat therefore collided with legal and political limits in Europe, exposing the gap between unilateral rhetoric and multilateral reality. The episode highlighted how his pressure tactics can provoke institutional counter-framing instead of compliance.","rationale":"AP documented EU-level pushback after Trump's Spain trade ultimatum.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["EU pushback","trade authority","Spain response","unilateral threat","institutional limits"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/43e0f13e7b1c7e6ebcc4b558474aacdc","source_title":"Trump threatens trade cutoff with Spain over Iran-war base dispute","source_publisher":"AP News","scores":make_scores("2026-03-03","Foreign Policy","Diplomatic Breakdown",7,6,8,6,3,3,7,10,"Trump's Spain pressure met legal and political resistance from EU trade structures.")},
{ "entry_number":1324,"title":"Trump Escalated an Alliance Dispute Into an Economic-Warfare Threat Mid-Conflict","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"Rather than isolating military planning from trade retaliation, AP described Trump doing the opposite with Spain. That convergence of war management and economic punishment signaled a presidency willing to weaponize market access in real time against allies. It added strategic friction exactly when coordinated diplomacy was already under strain.","rationale":"AP showed Trump converting alliance disagreement into immediate economic coercion.","category":"Foreign Policy","subcategory":"Economic Warfare","phase":"White House 2","keywords":["economic warfare","ally coercion","market access threat","strategic friction","war diplomacy"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/43e0f13e7b1c7e6ebcc4b558474aacdc","source_title":"Trump threatens trade cutoff with Spain over Iran-war base dispute","source_publisher":"AP News","scores":make_scores("2026-03-03","Foreign Policy","Economic Warfare",8,6,8,6,3,3,7,10,"Trump weaponized trade against an ally during active Iran-war diplomacy.")},
{ "entry_number":1325,"title":"Trump's Meeting Optics With European Leaders Exposed Deep Splits on Iran Strategy","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP's reporting around Trump's engagement with European leaders showed public disagreement instead of the unified front he sought. Visible rifts weaken deterrence narratives and complicate crisis bargaining with adversaries. Trump's coalition leadership claim took damage as partners publicly resisted his preferred escalation frame.","rationale":"AP reporting showed Trump's Iran coalition visibly fractured in leader-level diplomacy.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["leader meeting","European split","coalition fracture","deterrence narrative","Trump diplomacy"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/43e0f13e7b1c7e6ebcc4b558474aacdc","source_title":"Trump threatens trade cutoff with Spain over Iran-war base dispute","source_publisher":"AP News","scores":make_scores("2026-03-03","Foreign Policy","Diplomatic Breakdown",8,6,8,6,3,3,7,10,"Trump's leader-level diplomacy exposed widening allied disagreement over Iran policy.")},

{ "entry_number":1326,"title":"Trump Reversed Course and Said He Would Attend the White House Correspondents' Dinner","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP reported Trump announced he would attend the correspondents' dinner for the first time as president after years of boycott. The timing, during war controversy and media criticism, made the move look less like reconciliation and more like tactical image recalibration. Trump shifted from permanent hostility to conditional engagement when political optics changed.","rationale":"AP reported Trump's first-in-office dinner attendance after long anti-press posture.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["correspondents dinner","press relations","image reset","boycott reversal","media optics"],"metrics_key":"governance","source_url":"https://apnews.com/article/eb63e9bf024c56dab1fdefc732a42d5d","source_title":"In a first as president, Trump says he'll attend correspondents' dinner","source_publisher":"AP News","scores":make_scores("2026-03-03","Conspiracy Theories / Disinformation","Systematic Presidential Lying",6,4,6,5,3,4,7,10,"Trump abruptly reversed his anti-press dinner boycott during a high-pressure news cycle.")},
{ "entry_number":1327,"title":"Trump Softened Publicly Toward Press Rituals While Still Restricting Core War Transparency","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP's dinner story landed alongside criticism that Trump had avoided full public questioning during the Iran escalation window. The contrast was stark: symbolic outreach to media culture, but limited substantive accountability in crisis communication. Trump again separated theater from transparency and treated optics as a substitute for process.","rationale":"AP context showed symbolic media outreach paired with limited wartime transparency.","category":"Authoritarianism","subcategory":"Government Power Abuse","phase":"White House 2","keywords":["symbolic outreach","war transparency","media ritual","accountability gap","optics vs process"],"metrics_key":"governance","source_url":"https://apnews.com/article/eb63e9bf024c56dab1fdefc732a42d5d","source_title":"In a first as president, Trump says he'll attend correspondents' dinner","source_publisher":"AP News","scores":make_scores("2026-03-03","Authoritarianism","Government Power Abuse",7,6,7,7,3,3,7,10,"Trump offered media symbolism while withholding fuller crisis-accountability engagement.")},
{ "entry_number":1328,"title":"Trump Used Correspondents Dinner Attendance as Narrative Counterweight to Wartime Criticism","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"By signaling attendance at a high-visibility press event, Trump created a softer headline lane while facing intense scrutiny over Iran-war decisions. AP's framing made clear this was politically meaningful because it interrupted the prior pattern of total boycott. The move functioned as narrative balancing, not necessarily institutional openness.","rationale":"AP showed Trump introducing a softer media headline amid Iran-war pressure.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["narrative balancing","softer headline","media strategy","war criticism","boycott break"],"metrics_key":"governance","source_url":"https://apnews.com/article/eb63e9bf024c56dab1fdefc732a42d5d","source_title":"In a first as president, Trump says he'll attend correspondents' dinner","source_publisher":"AP News","scores":make_scores("2026-03-03","Conspiracy Theories / Disinformation","Systematic Presidential Lying",6,4,6,5,3,4,7,10,"Trump used symbolic media participation to offset harsher wartime coverage.")},
{ "entry_number":1329,"title":"Trump's White House Stagecraft and War Messaging Again Collided in Public Perception","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP noted Trump's continued focus on White House aesthetics and symbolic events while war communication remained contested. That juxtaposition fed criticism that he treats governance as branding architecture first and accountability second. In a conflict cycle, that style increases distrust because priorities appear performative rather than strategic.","rationale":"AP highlighted recurring tension between Trump's stagecraft focus and crisis communication needs.","category":"Authoritarianism","subcategory":"Government Power Abuse","phase":"White House 2","keywords":["stagecraft","branding governance","public perception","performative priorities","war messaging"],"metrics_key":"governance","source_url":"https://apnews.com/article/eb63e9bf024c56dab1fdefc732a42d5d","source_title":"In a first as president, Trump says he'll attend correspondents' dinner","source_publisher":"AP News","scores":make_scores("2026-03-03","Authoritarianism","Government Power Abuse",7,6,7,7,3,3,7,10,"Trump's symbolic stagecraft choices clashed with demands for clearer wartime leadership.")},
{ "entry_number":1330,"title":"Trump Preferred Controlled Appearances Over Full-Field Press Questions During Iran Crisis","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP reporting across the day reinforced that Trump favored tightly managed communication formats rather than open-ended press scrutiny while war stakes climbed. Controlled formats maximize message discipline but reduce adversarial fact-testing. That asymmetry was central to criticism of his crisis communications model.","rationale":"AP reported Trump's continued preference for controlled messaging during active conflict.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["controlled appearances","press questions","message discipline","fact testing","crisis model"],"metrics_key":"governance","source_url":"https://apnews.com/article/2aeb11fcfef4138c045be71fb7216792","source_title":"Trump takes unconventional approach to communicating on Iran war","source_publisher":"AP News","scores":make_scores("2026-03-03","Conspiracy Theories / Disinformation","Systematic Presidential Lying",7,5,7,6,3,4,8,10,"Trump relied on controlled appearances instead of broad press questioning in wartime.")},

{ "entry_number":1331,"title":"Trump's Iran War Strategy Strained the U.S.-U.K. Relationship in Public","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP reported a visible deterioration in U.S.-U.K. alignment as Starmer and Trump clashed over legal and strategic framing for strikes. The rift mattered because the special relationship is usually presented as a pillar of U.S. crisis legitimacy. Under Trump, that pillar looked negotiable and politically contingent.","rationale":"AP documented public U.S.-U.K. friction tied directly to Trump's Iran policy choices.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["US-UK strain","Starmer clash","special relationship","legal framing","Iran policy"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/fead317c818151d52ec249c8c21fee0b","source_title":"War with Iran strains US-UK relationship as Starmer and Trump disagree","source_publisher":"AP News","scores":make_scores("2026-03-03","Foreign Policy","Diplomatic Breakdown",8,6,8,6,3,3,7,10,"Trump's Iran escalation produced open U.S.-U.K. strategic friction.")},
{ "entry_number":1332,"title":"Trump Criticized U.K. Cooperation Levels as Britain Limited Direct Strike Support","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP described Trump publicly pressing London over what he viewed as insufficient cooperation, while the U.K. maintained legal and political limits on participation. That exchange made alliance bargaining unusually public during live conflict. Trump's pressure style again prioritized compulsion over consensus-building.","rationale":"AP showed Trump publicly pressing Britain for deeper wartime alignment.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["UK cooperation","public pressure","strike limits","alliance bargaining","consensus failure"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/fead317c818151d52ec249c8c21fee0b","source_title":"War with Iran strains US-UK relationship as Starmer and Trump disagree","source_publisher":"AP News","scores":make_scores("2026-03-03","Foreign Policy","Diplomatic Breakdown",8,6,8,6,3,3,7,10,"Trump openly pressured Britain over limited participation in Iran operations.")},
{ "entry_number":1333,"title":"Trump's Iran Escalation Undercut His Claim of Broad Democratic-Alliance Backing","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"With AP documenting disputes among close partners, Trump's coalition narrative faced a credibility gap. When allies publicly hedge, escalation appears less like shared security doctrine and more like leader-driven improvisation. That perception reduces external support and increases domestic skepticism about strategic necessity.","rationale":"AP coverage weakened Trump's broad-alliance support narrative.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["alliance backing","credibility gap","public hedge","strategic necessity","coalition narrative"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/fead317c818151d52ec249c8c21fee0b","source_title":"War with Iran strains US-UK relationship as Starmer and Trump disagree","source_publisher":"AP News","scores":make_scores("2026-03-03","Conspiracy Theories / Disinformation","Systematic Presidential Lying",7,5,8,6,3,4,8,10,"Trump's alliance-consensus claims weakened as partner resistance became public.")},
{ "entry_number":1334,"title":"Trump Simultaneously Pressured Spain and Clashed With Britain, Deepening Alliance Turbulence","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP's reporting across Europe showed Trump fighting on multiple diplomatic fronts at once: coercive threats to Spain and public friction with the U.K. In aggregate, that pattern reduced room for synchronized de-escalation strategy. Crisis leadership under Trump looked transactional and fragmented instead of coordinated.","rationale":"AP showed concurrent Trump disputes with multiple allies during conflict escalation.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["Spain and UK","multiple fronts","alliance turbulence","transactional leadership","de-escalation limits"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/fead317c818151d52ec249c8c21fee0b","source_title":"War with Iran strains US-UK relationship as Starmer and Trump disagree","source_publisher":"AP News","scores":make_scores("2026-03-03","Foreign Policy","Diplomatic Breakdown",8,6,8,6,3,3,7,10,"Trump's simultaneous disputes with Spain and Britain deepened alliance fragmentation.")},
{ "entry_number":1335,"title":"Trump's Iran War Expanded Into a Region-Wide Economic Shock Cycle","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"Global market and energy reporting on March 3 described falling equities and rising oil as the conflict spread. Under Trump's escalation posture, security shocks and macroeconomic stress began reinforcing each other, increasing downstream costs for households and allies. The conflict was no longer just tactical; it was system-level disruption.","rationale":"Market coverage linked Trump's conflict expansion to broad energy and risk shock effects.","category":"Foreign Policy","subcategory":"Economic Warfare","phase":"White House 2","keywords":["market drop","oil spike","economic shock","regional spread","system disruption"],"metrics_key":"war","source_url":"https://www.theguardian.com/business/2026/mar/03/global-stock-markets-iran-war-gas-oil-prices-ftse-100","source_title":"Global stock markets sink and oil surges amid Iran war fears","source_publisher":"The Guardian","scores":make_scores("2026-03-03","Foreign Policy","Economic Warfare",8,6,9,6,3,3,7,10,"Trump-era escalation correlated with market declines and oil-price shocks.")},

{ "entry_number":1336,"title":"Trump's War Timeline Coincided With Rising Civilian-Harm Allegations and Legal Scrutiny","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP live war coverage included repeated warnings tied to civilian-site impacts and possible legal implications as strikes expanded. Even without final adjudication, the accumulation of high-risk incidents raised reputational and diplomatic costs for Washington. Trump's strategy intensified legal and moral exposure alongside military pressure.","rationale":"AP reporting tied conflict expansion under Trump to increasing civilian-harm scrutiny.","category":"Human Rights Violations","subcategory":"Civilian Harm","phase":"White House 2","keywords":["civilian harm","legal scrutiny","war exposure","reputational cost","strike fallout"],"metrics_key":"war","source_url":"https://apnews.com/live/iran-war-israel-trump-03-03-2026","source_title":"Live updates: Iran war and Trump administration response","source_publisher":"AP News","scores":make_scores("2026-03-03","Human Rights Violations","Civilian Harm",9,7,9,6,3,3,7,10,"Trump's escalation cycle increased scrutiny over civilian-impact and legal risk.")},
{ "entry_number":1337,"title":"Trump-Era Escalation Drove Evacuation Waves and Emergency Travel Disruptions","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP live updates tracked expanding evacuation advisories and heavy aviation disruption as the conflict widened. These civilian-protection measures are indirect indicators of strategic instability: when governments pull people out at scale, confidence in near-term de-escalation is low. Trump's timeline pushed policy from deterrence into emergency management.","rationale":"AP documented broad evacuation and travel disruption signals during Trump's escalation week.","category":"Human Rights Violations","subcategory":"Public Welfare Harm","phase":"White House 2","keywords":["evacuations","travel disruption","civilian protection","emergency management","de-escalation doubt"],"metrics_key":"war","source_url":"https://apnews.com/live/iran-war-israel-trump-03-03-2026","source_title":"Live updates: Iran war and Trump administration response","source_publisher":"AP News","scores":make_scores("2026-03-03","Human Rights Violations","Public Welfare Harm",8,6,9,6,3,3,7,10,"Trump's war posture triggered broad evacuation and travel-disruption responses.")},
{ "entry_number":1338,"title":"Trump Said Iran War Could Last Weeks While Exit Strategy Questions Grew","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP live updates carried Trump's acknowledgement that the conflict could continue for weeks, a notable shift from short-horizon confidence language. Publicly extending the timeline without fully detailed end-state criteria intensified scrutiny over planning depth. The statement made clear this was not a quick symbolic strike cycle but an open-ended risk window.","rationale":"AP captured Trump's own admission that the Iran conflict could be prolonged.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["weeks-long war","exit strategy","timeline shift","open-ended risk","planning depth"],"metrics_key":"war","source_url":"https://apnews.com/live/iran-war-israel-trump-03-03-2026","source_title":"Live updates: Iran war and Trump administration response","source_publisher":"AP News","scores":make_scores("2026-03-03","Foreign Policy","Military Escalation",8,6,9,6,3,3,7,10,"Trump acknowledged a weeks-long conflict horizon without full end-state clarity.")},
{ "entry_number":1339,"title":"Trump Administration Urged Americans in Many Countries to Depart as War Risks Spread","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP detailed broad State Department departure guidance as conflict-related risk spilled across multiple states. Government evacuation posture on that scale contradicts claims of tightly contained escalation. Under Trump, official advisories themselves became evidence that regional spillover probability was high.","rationale":"AP showed large-scale U.S. departure advisories during Trump's war expansion.","category":"Human Rights Violations","subcategory":"Public Welfare Harm","phase":"White House 2","keywords":["departure advisory","State Department","regional spillover","risk spread","citizen safety"],"metrics_key":"war","source_url":"https://apnews.com/live/iran-war-israel-trump-03-03-2026","source_title":"Live updates: Iran war and Trump administration response","source_publisher":"AP News","scores":make_scores("2026-03-03","Human Rights Violations","Public Welfare Harm",8,6,9,6,3,3,7,10,"Trump-era escalation prompted broad U.S. departure warnings across countries.")},
{ "entry_number":1340,"title":"Trump's 'Could Last Weeks' Message Undercut Earlier Fast-Resolution Assumptions","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"By publicly stating the Iran war might last weeks, Trump moved away from implications of quick closure. AP's timeline showed the political consequence: once duration expectations reset upward, accountability questions on casualties, costs and congressional role intensify. The new timeline made strategic overreach harder to dismiss.","rationale":"AP showed Trump's own timeline revision increasing accountability pressure.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["timeline revision","fast resolution","accountability pressure","war costs","strategic overreach"],"metrics_key":"war","source_url":"https://apnews.com/live/iran-war-israel-trump-03-03-2026","source_title":"Live updates: Iran war and Trump administration response","source_publisher":"AP News","scores":make_scores("2026-03-03","Conspiracy Theories / Disinformation","Systematic Presidential Lying",7,5,8,6,3,4,8,10,"Trump's revised war-duration framing heightened scrutiny over prior messaging.")},

{ "entry_number":1341,"title":"Trump Announced Major Iran Combat Operations in a Pre-Recorded Social Video","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's full-text statement publication confirmed Trump unveiled major combat operations through a recorded platform message rather than immediate open questioning. The format gave maximum message control at the exact moment legal, strategic and humanitarian questions were peaking. It exemplified Trump's preference for unilateral narrative release over adversarial briefing.","rationale":"AP showed Trump delivering war-announcement messaging through controlled prerecorded format.","category":"Authoritarianism","subcategory":"Government Power Abuse","phase":"White House 2","keywords":["pre-recorded statement","Truth Social","combat announcement","message control","press bypass"],"metrics_key":"governance","source_url":"https://apnews.com/article/f662a4f3378535d81197be699fb35a3e","source_title":"Read President Trump's statement on Iran in full","source_publisher":"AP News","scores":make_scores("2026-02-28","Authoritarianism","Government Power Abuse",8,7,8,7,3,3,7,10,"Trump announced major combat through a controlled video format rather than open press scrutiny.")},
{ "entry_number":1342,"title":"Trump Called on Iranian Security Forces to Surrender for Immunity or 'Face Certain Death'","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's published statement text captured Trump issuing stark surrender-or-destruction language toward Iranian forces. Beyond battlefield signaling, the rhetoric reflected maximal coercive framing that narrowed diplomatic off-ramps in public perception. Trump's communication style favored intimidation clarity over de-escalation ambiguity.","rationale":"AP statement text documented Trump's explicit surrender-or-death wartime rhetoric.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["surrender demand","certain death","coercive rhetoric","off-ramp risk","wartime language"],"metrics_key":"war","source_url":"https://apnews.com/article/f662a4f3378535d81197be699fb35a3e","source_title":"Read President Trump's statement on Iran in full","source_publisher":"AP News","scores":make_scores("2026-02-28","Foreign Policy","Military Escalation",9,7,9,6,3,3,7,10,"Trump used extreme coercive language that reduced perceived diplomatic space.")},
{ "entry_number":1343,"title":"Trump's Iran Speech Mixed Regime-Collapse Themes With His Anti-Forever-War Brand","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's text release highlighted a contradiction at the center of Trump's messaging: anti-forever-war identity politics alongside rhetoric implying major regime-level outcomes. That mismatch deepened skepticism among both critics and former supporters who heard campaign restraint promises. Trump's narrative attempted to occupy opposing positions simultaneously.","rationale":"AP statement context showed contradiction between Trump's anti-war branding and regime-level rhetoric.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["forever war","regime rhetoric","brand contradiction","supporter skepticism","message mismatch"],"metrics_key":"war","source_url":"https://apnews.com/article/f662a4f3378535d81197be699fb35a3e","source_title":"Read President Trump's statement on Iran in full","source_publisher":"AP News","scores":make_scores("2026-02-28","Conspiracy Theories / Disinformation","Systematic Presidential Lying",8,6,8,6,4,4,8,10,"Trump's war statement clashed with his anti-forever-war political identity.")},
{ "entry_number":1344,"title":"Satellite Images Showed Fresh Natanz Damage as Trump Warned Iran Was Rebuilding","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP reported satellite evidence of new damage at Natanz while Trump repeated warnings about Iranian rebuilding efforts. The dual claim environment created a verification challenge: battlefield damage, restricted inspections and competing strategic narratives all at once. Under Trump's messaging, confidence relied heavily on selective evidence access.","rationale":"AP combined Natanz imagery findings with Trump rebuilding claims amid verification gaps.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["Natanz damage","satellite imagery","rebuilding claim","verification gap","inspection limits"],"metrics_key":"war","source_url":"https://apnews.com/article/e42a4711f6d350d14c10e5f9981eca46","source_title":"Satellite images show damage to Iran's Natanz nuclear facility","source_publisher":"AP News","scores":make_scores("2026-03-03","Foreign Policy","Military Escalation",8,6,8,6,3,3,7,10,"Trump's Natanz narrative operated amid restricted verification and contested evidence.")},
{ "entry_number":1345,"title":"Trump's Nuclear-Claim Messaging Faced Credibility Pressure as Inspector Access Remained Limited","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP noted the IAEA could not fully verify key enrichment stockpile details after access restrictions, even as Trump made high-confidence public claims about Iranian capabilities and intent. This asymmetry between certainty in rhetoric and limits in verification intensified credibility debates. Trump's communication leaned definitive while facts remained partially constrained.","rationale":"AP reporting showed verification limits colliding with Trump's high-certainty nuclear claims.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["IAEA access","nuclear claims","credibility pressure","verification limits","high-certainty rhetoric"],"metrics_key":"war","source_url":"https://apnews.com/article/e42a4711f6d350d14c10e5f9981eca46","source_title":"Satellite images show damage to Iran's Natanz nuclear facility","source_publisher":"AP News","scores":make_scores("2026-03-03","Conspiracy Theories / Disinformation","Systematic Presidential Lying",8,6,8,6,4,4,8,10,"Trump made high-certainty nuclear assertions while independent verification remained constrained.")},
]

entry_cols=["entry_number","title","date_start","date_end","synopsis","rationale","category","subcategory","keywords","age","phase","impressions","reach_estimate","financial_cost_usd","public_reaction","fact_check","fact_check_sources","scores"]
score_cols=["entry_number","insanity","absurdity","danger","authoritarianism","lawlessness","credibility_risk","recency_intensity","impact_scope","rationale_short","rationale_detail"]
source_cols=["entry_number","url","title","publisher","date_published","source_type"]

entry_vals=[]; score_vals=[]; source_vals=[]; keyword_vals=[]
for e in entries:
    m=metrics[e["metrics_key"]]
    e["impressions"]=m["impressions"]; e["reach_estimate"]=m["reach_estimate"]; e["financial_cost_usd"]=m["financial_cost_usd"]; e["public_reaction"]=m["public_reaction"]; e["age"]=calc_age(e["date_start"])
    s=e["scores"]
    entry_vals.append("("+", ".join([
        str(e["entry_number"]),f"'{sql_escape(e['title'])}'",f"'{e['date_start']}'",f"'{e['date_end']}'",f"'{sql_escape(e['synopsis'])}'",f"'{sql_escape(e['rationale'])}'",f"'{sql_escape(e['category'])}'",f"'{sql_escape(e['subcategory'])}'",arr_sql(e["keywords"]),str(e["age"]),f"'{sql_escape(e['phase'])}'",str(e["impressions"]),str(e["reach_estimate"]),str(e["financial_cost_usd"]),json_sql(e["public_reaction"]),"NULL","ARRAY[]::text[]",json_sql(s)
    ])+")")
    score_vals.append("("+", ".join([
        str(e["entry_number"]),str(s["insanity"]),str(s["absurdity"]),str(s["danger"]),str(s["authoritarianism"]),str(s["lawlessness"]),str(s["credibility_risk"]),str(s["recency_intensity"]),str(s["impact_scope"]),f"'{sql_escape(s['rationale_short'])}'",f"'{sql_escape(s['rationale_detail'])}'"
    ])+")")
    source_vals.append("("+", ".join([
        str(e["entry_number"]),f"'{sql_escape(e['source_url'])}'",f"'{sql_escape(e['source_title'])}'",f"'{sql_escape(e['source_publisher'])}'",f"'{e['date_start']}'",f"'news'"
    ])+")")
    for kw in e["keywords"]: keyword_vals.append("("+", ".join([str(e["entry_number"]),f"'{sql_escape(kw)}'"])+")")

sql_entries="INSERT INTO public.trump_entries ("+", ".join(entry_cols)+") VALUES\n"+",\n".join(entry_vals)+"\nON CONFLICT DO NOTHING;"
sql_scores="INSERT INTO public.trump_individual_scores ("+", ".join(score_cols)+") VALUES\n"+",\n".join(score_vals)+"\nON CONFLICT DO NOTHING;"
sql_sources="INSERT INTO public.trump_sources ("+", ".join(source_cols)+") VALUES\n"+",\n".join(source_vals)+";"
sql_keywords="INSERT INTO public.trump_keywords (entry_number, keyword) VALUES\n"+",\n".join(keyword_vals)+"\nON CONFLICT DO NOTHING;"
print(json.dumps([sql_entries,sql_scores,sql_sources,sql_keywords],indent=2))
