import json
from datetime import datetime

months=["Jan.","Feb.","Mar.","Apr.","May","Jun.","Jul.","Aug.","Sep.","Oct.","Nov.","Dec."]
birth_date=datetime(1946,6,14)

def format_date(date_str:str)->str:
    d=datetime.strptime(date_str,"%Y-%m-%d")
    return f"{months[d.month-1]} {d.day}, {d.year}"

def calc_age(date_str:str)->int:
    d=datetime.strptime(date_str,"%Y-%m-%d")
    a=d.year-birth_date.year
    if (d.month,d.day)<(birth_date.month,birth_date.day): a-=1
    return a

def sql_escape(v:str)->str: return v.replace("'","''")
def json_sql(o)->str: return "'"+json.dumps(o,separators=(",",":"),ensure_ascii=True).replace("'","''")+"'::jsonb"
def arr_sql(items)->str:
    if not items: return "ARRAY[]::text[]"
    return "ARRAY["+",".join("'"+sql_escape(x)+"'" for x in items)+"]::text[]"

def make_scores(date_start,category,subcategory,danger,lawlessness,impact_scope,authoritarianism,insanity,absurdity,credibility_risk,recency_intensity,rationale_short):
    return {
        "danger":danger,"insanity":insanity,"absurdity":absurdity,"lawlessness":lawlessness,"impact_scope":impact_scope,
        "rationale_short":rationale_short,"authoritarianism":authoritarianism,"credibility_risk":credibility_risk,
        "rationale_detail":f"{category}: {subcategory}. On {format_date(date_start)}, {rationale_short}","recency_intensity":recency_intensity,
    }

metrics={
    "promise":{"impressions":124000000,"reach_estimate":420000000,"financial_cost_usd":88000000,"public_reaction":{"negative":72,"neutral":20,"positive":8}},
    "immigration":{"impressions":156000000,"reach_estimate":545000000,"financial_cost_usd":190000000,"public_reaction":{"negative":78,"neutral":16,"positive":6}},
    "economy":{"impressions":146000000,"reach_estimate":512000000,"financial_cost_usd":240000000,"public_reaction":{"negative":74,"neutral":18,"positive":8}},
    "election":{"impressions":132000000,"reach_estimate":448000000,"financial_cost_usd":110000000,"public_reaction":{"negative":76,"neutral":17,"positive":7}},
}

u="https://apnews.com/projects/trump-campaign-promise-tracker/"
entries=[
{ "entry_number":1271,"title":"Trump's Promise Dashboard Showed More Complicated and In-Progress Items Than Kept","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's tracker snapshot showed Trump's second-term promise list split across kept, in-progress and complicated buckets, with unresolved categories outweighing clean completions. The distribution mattered because it challenged campaign messaging that implied near-total execution. By quantifying status rather than repeating talking points, the dashboard exposed the difference between declaration and delivery.","rationale":"AP's status distribution showed unresolved promises outnumbering clear completions under Trump.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["AP tracker","promise status","kept vs complicated","delivery gap","Trump claims"],"metrics_key":"promise","scores":make_scores("2026-02-28","Conspiracy Theories / Disinformation","Systematic Presidential Lying",6,4,7,5,3,4,8,9,"AP status buckets showed unresolved promises outweighing fully kept items.")},
{ "entry_number":1272,"title":"Trump Classified-Records Promise Marked Kept While Broader Transparency Disputes Persisted","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's tracker listed Trump's promise to release key classified files as kept, but the broader information-governance landscape remained contested in parallel controversies. The contrast highlighted a recurring dynamic: a narrow tracked promise can score as complete while adjacent transparency issues continue to fuel institutional mistrust. Completion metrics and accountability confidence are not always the same thing.","rationale":"A tracked classified-records promise was marked kept despite wider transparency conflicts.","category":"Government Corruption","subcategory":"Transparency Obstruction","phase":"White House 2","keywords":["classified files","kept status","transparency","AP tracker","information governance"],"metrics_key":"promise","scores":make_scores("2026-02-28","Government Corruption","Transparency Obstruction",6,5,6,5,3,3,6,9,"AP marked a classified-records promise kept while broader transparency disputes persisted.")},
{ "entry_number":1273,"title":"Trump School-Funding Threat Over Vaccine Mandates Rated 'Complicated' by AP Tracker","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's tracker categorized Trump's pledge to cut federal money to schools with vaccine requirements as complicated rather than resolved. The status suggested significant legal, political, or implementation friction despite aggressive campaign framing. The promise became an example of how culturally charged proposals can stall once they meet institutional constraints.","rationale":"AP rated Trump's school-funding punishment promise as complicated, not completed.","category":"Authoritarianism","subcategory":"Government Power Abuse","phase":"White House 2","keywords":["schools","vaccine mandates","federal funding","complicated status","AP tracker"],"metrics_key":"promise","scores":make_scores("2026-02-28","Authoritarianism","Government Power Abuse",6,5,6,7,3,3,6,9,"AP rated Trump's school-funding punishment promise as complicated.")},
{ "entry_number":1274,"title":"Trump Plan to Shut Down Education Department Listed as In Progress, Not Completed","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's promise tracker showed Trump's push to dismantle the U.S. Department of Education as in progress, indicating partial movement without final execution. The gap between political certainty and administrative finality reflected the structural difficulty of dismantling major federal institutions. The status weakened claims of finished delivery.","rationale":"A headline promise to close the Education Department remained in progress on AP's tracker.","category":"Authoritarianism","subcategory":"Government Power Abuse","phase":"White House 2","keywords":["Education Department","in progress","federal agencies","institutional rollback","promise tracking"],"metrics_key":"promise","scores":make_scores("2026-02-28","Authoritarianism","Government Power Abuse",7,6,7,8,3,3,6,9,"AP marked Trump's Education Department shutdown promise as still in progress.")},
{ "entry_number":1275,"title":"Trump EV-Mandate Rollback Promise Still In Progress According to AP","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's tracker listed Trump's pledge to reverse Biden-era electric-vehicle mandates as in progress rather than completed. The status reflected policy movement with unresolved legal and regulatory endpoints. In practical terms, in-progress designations show that headline reversals can take longer and encounter more friction than campaign rhetoric implies.","rationale":"EV-mandate rollback was still in progress, undercutting claims of full completion.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["EV mandate","in progress","regulatory rollback","AP promises","completion gap"],"metrics_key":"economy","scores":make_scores("2026-02-28","Conspiracy Theories / Disinformation","Systematic Presidential Lying",6,4,7,5,3,3,7,9,"AP showed Trump's EV rollback promise remained in progress.")},
{ "entry_number":1276,"title":"Trump Emissions-Waiver Reversal Promise Also Stayed In Progress on AP Tracker","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's tracker placed Trump's pledge to terminate emissions waivers in the in-progress category, signaling unresolved implementation status. The classification highlighted that legal durability and final regulatory effect lagged behind campaign declarations. As with other items, the scoreboard challenged broad claims of total promise completion.","rationale":"AP rated emissions-waiver rollback as ongoing rather than complete under Trump.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["emissions waivers","in progress","environment rollback","AP tracker","policy status"],"metrics_key":"economy","scores":make_scores("2026-02-28","Conspiracy Theories / Disinformation","Systematic Presidential Lying",6,4,7,5,3,3,7,9,"AP listed Trump's emissions-waiver rollback promise as in progress.")},
{ "entry_number":1277,"title":"Trump's Energy-Emergency Pledge Registered as Kept in AP Promise Tracker","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's tracker showed Trump's declaration of a national energy emergency as a kept promise, reflecting formal action on one of his energy-platform priorities. Even so, kept status on declaration-type promises did not automatically resolve downstream outcomes like price targets or infrastructure constraints. The entry illustrated how procedural completion can coexist with substantive disputes.","rationale":"AP marked Trump's energy-emergency pledge as kept through formal action.","category":"Foreign Policy","subcategory":"Economic Warfare","phase":"White House 2","keywords":["energy emergency","kept promise","AP tracker","formal action","policy outcomes"],"metrics_key":"economy","scores":make_scores("2026-02-28","Foreign Policy","Economic Warfare",6,4,7,5,3,3,6,9,"AP marked Trump's energy-emergency promise kept through formal declaration.")},
{ "entry_number":1278,"title":"Trump Paris-Agreement Exit Promise Marked Kept While Climate Fallout Debate Continued","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's tracker listed Trump's withdrawal-from-Paris pledge as kept, indicating procedural completion of a major climate-policy reversal. The classification did not settle policy impact debates, but it confirmed alignment between rhetoric and this specific action. The case showed how promise tracking can separate binary delivery from broader consequence analysis.","rationale":"AP marked Trump's Paris-exit pledge kept, even as climate-policy consequences remained contested.","category":"Foreign Policy","subcategory":"Economic Warfare","phase":"White House 2","keywords":["Paris Agreement","withdrawal","kept status","climate policy","AP promises"],"metrics_key":"economy","scores":make_scores("2026-02-28","Foreign Policy","Economic Warfare",6,4,7,5,3,3,6,9,"AP marked Trump's Paris-withdrawal promise kept.")},
{ "entry_number":1279,"title":"Trump Promise to Cut Energy Prices by Half Was Rated 'Complicated'","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's tracker classified Trump's pledge to halve energy prices within a defined timeframe as complicated. The label indicated mixed movement without conclusive attainment of the stated benchmark. This is exactly the type of promise where headline simplicity collides with market complexity, regulatory lag and global supply dynamics.","rationale":"AP rated Trump's dramatic energy-price-cut pledge as complicated rather than delivered.","category":"Grift / Financial Exploitation","subcategory":"Government Resource Abuse","phase":"White House 2","keywords":["energy prices","complicated status","benchmark promise","AP tracker","cost claims"],"metrics_key":"economy","scores":make_scores("2026-02-28","Grift / Financial Exploitation","Government Resource Abuse",6,4,7,5,3,3,7,9,"AP rated Trump's promised energy-price halving as complicated.")},
{ "entry_number":1280,"title":"Trump's 'End Ukraine War Before Inauguration' Promise Logged as Complicated","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP tracking showed Trump's promise to end the Russia-Ukraine war before taking office in a complicated state rather than fulfilled. The status reflected unresolved diplomatic outcomes despite continued negotiations. It reinforced the mismatch between absolute campaign commitments and constraints of active international conflict.","rationale":"AP marked Trump's pre-inauguration Ukraine-war ending pledge as complicated.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["Ukraine war","pre-inauguration promise","complicated","AP tracker","foreign policy claim"],"metrics_key":"promise","scores":make_scores("2026-02-28","Conspiracy Theories / Disinformation","Systematic Presidential Lying",7,4,8,5,3,4,8,9,"AP tracked Trump's pre-inauguration Ukraine-war promise as complicated, not complete.")},
{ "entry_number":1281,"title":"Trump 'Deep State' Purge Promise Stayed In Progress on AP Dashboard","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's promise tracker listed Trump's pledge to uproot what he calls the deep state as in progress. That status indicates ongoing bureaucratic confrontation without clear closure, and it carries institutional consequences for civil-service independence. The framing of career officials as enemies continued to function as both political narrative and governance strategy.","rationale":"AP listed Trump's deep-state purge promise as in progress with continuing institutional implications.","category":"Authoritarianism","subcategory":"Government Power Abuse","phase":"White House 2","keywords":["deep state", "civil service", "purge", "in progress", "AP tracker"],"metrics_key":"promise","scores":make_scores("2026-02-28","Authoritarianism","Government Power Abuse",7,6,7,8,4,3,7,9,"AP tracked Trump's deep-state purge pledge as in progress.")},
{ "entry_number":1282,"title":"Trump IVF-Cost Promise Rated 'Complicated' Instead of Delivered","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's tracker marked Trump's IVF affordability pledge as complicated, signaling partial movement without full delivery. Reproductive-health financing promises are highly visible and politically potent, making unresolved status particularly consequential. The rating challenged rhetoric that presented the commitment as straightforward and complete.","rationale":"AP rated Trump's IVF treatment affordability promise as complicated, not fulfilled.","category":"Human Rights Violations","subcategory":"Public Welfare Harm","phase":"White House 2","keywords":["IVF", "healthcare costs", "complicated promise", "AP tracker", "delivery gap"],"metrics_key":"promise","scores":make_scores("2026-02-28","Human Rights Violations","Public Welfare Harm",6,4,7,5,3,3,7,9,"AP classified Trump's IVF affordability promise as complicated.")},
{ "entry_number":1283,"title":"Trump's 'Largest Deportation in U.S. History' Promise Remained In Progress","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's tracker listed Trump's largest-deportation pledge as in progress, reflecting active enforcement expansion without endpoint completion. The status underscored that immigration hardline agendas often proceed through rolling administrative escalation rather than one-time delivery milestones. In policy terms, in-progress can still mean major real-world impact.","rationale":"AP tracked Trump's mass-deportation promise as in progress amid continuing enforcement expansion.","category":"Human Rights Violations","subcategory":"Immigration Crackdown","phase":"White House 2","keywords":["deportation", "in progress", "immigration enforcement", "AP tracker", "mass removal"],"metrics_key":"immigration","scores":make_scores("2026-02-28","Human Rights Violations","Immigration Crackdown",8,7,8,8,3,3,6,9,"AP listed Trump's largest-deportation pledge as in progress amid ongoing crackdown." )},
{ "entry_number":1284,"title":"Trump Birthright-Citizenship Promise Still Marked 'Complicated' by AP","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's status tracker categorized Trump's pledge to end birthright citizenship as complicated, highlighting constitutional and legal barriers to implementation. The rating suggested that aggressive campaign assertions had collided with judicial and structural constraints. This became another case where rhetoric outpaced executable policy reality.","rationale":"AP rated Trump's birthright-citizenship termination pledge as complicated due to legal constraints.","category":"Election Interference","subcategory":"Election Interference","phase":"White House 2","keywords":["birthright citizenship", "constitutional challenge", "complicated", "AP promises", "legal barriers"],"metrics_key":"election","scores":make_scores("2026-02-28","Election Interference","Election Interference",7,6,7,7,3,3,7,9,"AP marked Trump's birthright-citizenship promise as complicated.")},
{ "entry_number":1285,"title":"Trump Student-Visa Crackdown Promise on Protesters Was Rated 'Complicated'","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's tracker marked Trump's promise to revoke student visas tied to certain protest categories as complicated. The status reflects legal and procedural constraints around immigration, speech and campus enforcement boundaries. It also indicates that high-friction civil-liberties proposals tend to stall in implementation even when politically amplified.","rationale":"AP classified Trump's student-visa revocation pledge as complicated amid legal and rights constraints.","category":"Human Rights Violations","subcategory":"Immigration Crackdown","phase":"White House 2","keywords":["student visas", "protester crackdown", "complicated status", "civil liberties", "AP tracker"],"metrics_key":"immigration","scores":make_scores("2026-02-28","Human Rights Violations","Immigration Crackdown",7,6,7,7,3,3,7,9,"AP rated Trump's student-visa crackdown pledge as complicated.")},
{ "entry_number":1286,"title":"Trump Broad Deportation Promise for 'Criminal Migrants' Also Landed in 'Complicated' Bucket","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"Another immigration pledge on AP's tracker was classified as complicated, showing limited conversion of broad campaign language into fully realized policy outcomes. The repeated complicated status across related deportation promises suggested implementation friction beyond messaging intensity. Enforcement rhetoric remained maximal while legal and institutional pathways remained constrained.","rationale":"AP tracker showed another flagship Trump deportation pledge stalled in complicated status.","category":"Human Rights Violations","subcategory":"Immigration Crackdown","phase":"White House 2","keywords":["criminal migrants", "deportation pledge", "complicated", "implementation friction", "AP promises"],"metrics_key":"immigration","scores":make_scores("2026-02-28","Human Rights Violations","Immigration Crackdown",7,6,7,7,3,3,7,9,"AP classified a major Trump deportation pledge as complicated rather than completed.")},
{ "entry_number":1287,"title":"Trump Jan. 6 Clemency Promise Was Marked Kept in AP Tracker","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's tracker listed Trump's pledge to pardon many January 6 defendants as kept, marking one of the clearer delivery items on the dashboard. The kept rating confirmed execution of a politically consequential promise with major democratic-norm implications. It also illustrated that not all high-impact promises faced implementation friction.","rationale":"AP recorded Trump's Jan. 6 clemency pledge as kept.","category":"Insurrection / Coup Attempts","subcategory":"Democratic Institution Undermining","phase":"White House 2","keywords":["Jan 6 pardons", "kept promise", "clemency", "AP tracker", "democratic norms"],"metrics_key":"election","scores":make_scores("2026-02-28","Insurrection / Coup Attempts","Democratic Institution Undermining",8,8,8,8,3,3,6,9,"AP marked Trump's Jan. 6 clemency pledge as kept.")},
{ "entry_number":1288,"title":"Trump Broad Tariff Promise Stayed 'Complicated' in AP Promise Tracker","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's dashboard categorized Trump's promise to impose sweeping tariffs on job-offshoring countries as complicated. The label reflected legal constraints, court scrutiny, and trade-partner responses that limited straightforward completion. Tariff politics remained central to messaging, but the tracker showed execution complexity far beyond campaign slogans.","rationale":"AP rated Trump's sweeping tariff pledge as complicated amid legal and trade constraints.","category":"Foreign Policy","subcategory":"Economic Warfare","phase":"White House 2","keywords":["tariffs", "offshoring", "complicated promise", "trade constraints", "AP tracker"],"metrics_key":"economy","scores":make_scores("2026-02-28","Foreign Policy","Economic Warfare",7,5,7,6,3,3,7,9,"AP classified Trump's broad tariff promise as complicated.")},
{ "entry_number":1289,"title":"Trump Corporate-Tax-Cut-to-15% Promise Also Classified as 'Complicated'","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's tracker showed Trump's corporate tax-cut pledge remained in complicated territory rather than cleanly delivered. The classification suggested partial legislative movement without full alignment to campaign terms. It reinforced a broader pattern where fiscal promises required tradeoffs that diluted headline claims.","rationale":"AP rated Trump's corporate-tax 15% promise as complicated rather than fully delivered.","category":"Grift / Financial Exploitation","subcategory":"Government Resource Abuse","phase":"White House 2","keywords":["corporate tax", "15 percent", "complicated", "fiscal tradeoffs", "AP promises"],"metrics_key":"economy","scores":make_scores("2026-02-28","Grift / Financial Exploitation","Government Resource Abuse",6,4,7,5,3,3,7,9,"AP listed Trump's corporate-tax-cut promise as complicated.")},
{ "entry_number":1290,"title":"Trump No-Tax-on-Tips Promise Registered as Kept on AP Dashboard","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's promise tracker marked Trump's no-tax-on-tips commitment as kept, placing it among the smaller set of fully delivered campaign items. The kept status provided one of the administration's clearer scorecard wins. Still, isolated kept items did not erase the larger unresolved balance visible across the tracker.","rationale":"AP recorded no-tax-on-tips as a kept Trump promise amid broader unresolved totals.","category":"Grift / Financial Exploitation","subcategory":"Government Resource Abuse","phase":"White House 2","keywords":["tips tax", "kept promise", "AP tracker", "fiscal policy", "campaign delivery"],"metrics_key":"economy","scores":make_scores("2026-02-28","Grift / Financial Exploitation","Government Resource Abuse",6,4,7,5,3,3,6,9,"AP marked Trump's no-tax-on-tips pledge as kept.")},
{ "entry_number":1291,"title":"Trump No-Tax-on-Social-Security Promise Stayed In Progress","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's tracker categorized Trump's no-tax-on-Social-Security pledge as in progress, indicating movement but not final completion. The in-progress status mirrored fiscal and legislative complexity around entitlement-related tax changes. In scoreboard terms, the promise remained open rather than banked.","rationale":"AP listed Trump's no-tax-on-Social-Security pledge as in progress.","category":"Grift / Financial Exploitation","subcategory":"Government Resource Abuse","phase":"White House 2","keywords":["Social Security", "in progress", "tax pledge", "entitlement policy", "AP tracker"],"metrics_key":"economy","scores":make_scores("2026-02-28","Grift / Financial Exploitation","Government Resource Abuse",6,4,7,5,3,3,7,9,"AP tracked Trump's no-tax-on-Social-Security promise as in progress.")},
{ "entry_number":1292,"title":"Trump Full Social-Security-Tax-Elimination Promise Rated 'Complicated'","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's dashboard showed Trump's broader Social Security tax-elimination pledge as complicated, separate from narrower in-progress measures. That distinction exposed how partial tax relief can be presented as fulfillment even when core headline language is not met. The tracker made that gap explicit.","rationale":"AP rated full Social Security tax elimination as complicated, not delivered.","category":"Grift / Financial Exploitation","subcategory":"Government Resource Abuse","phase":"White House 2","keywords":["Social Security tax elimination", "complicated", "partial relief", "promise gap", "AP"],"metrics_key":"economy","scores":make_scores("2026-02-28","Grift / Financial Exploitation","Government Resource Abuse",6,4,7,5,3,3,7,9,"AP classified Trump's full Social Security tax-elimination promise as complicated.")},
{ "entry_number":1293,"title":"Trump No-Tax-on-Overtime Promise Was Also Marked 'Complicated'","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's tracker listed Trump's no-tax-on-overtime promise as complicated, reflecting unresolved implementation details and legislative barriers. The status reinforced the dashboard's broader message: many economic promises remained partially executed or stalled despite confident public messaging. Complex tax pledges proved resistant to one-cycle completion.","rationale":"AP marked Trump's overtime-tax promise as complicated due to unresolved implementation.","category":"Grift / Financial Exploitation","subcategory":"Government Resource Abuse","phase":"White House 2","keywords":["overtime tax", "complicated", "implementation barriers", "tax policy", "AP tracker"],"metrics_key":"economy","scores":make_scores("2026-02-28","Grift / Financial Exploitation","Government Resource Abuse",6,4,7,5,3,3,7,9,"AP rated Trump's no-tax-on-overtime promise as complicated.")},
{ "entry_number":1294,"title":"Trump Car-Loan-Interest Promise for U.S.-Made Cars Remained In Progress","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's promise tracker categorized Trump's car-loan-interest pledge for American-made vehicles as in progress, not completed. The designation signaled movement without full policy closure, again underscoring that niche economic promises can linger between announcement and implementation. The status challenged blanket claims of comprehensive completion.","rationale":"AP listed Trump's car-loan-interest promise as in progress rather than complete.","category":"Grift / Financial Exploitation","subcategory":"Government Resource Abuse","phase":"White House 2","keywords":["car loans", "American-made cars", "in progress", "economic promise", "AP tracker"],"metrics_key":"economy","scores":make_scores("2026-02-28","Grift / Financial Exploitation","Government Resource Abuse",6,4,7,5,3,3,7,9,"AP tracked Trump's car-loan-interest pledge as in progress.")},
{ "entry_number":1295,"title":"Trump Promise Tracking Showed Immigration and Tariff Items Clustered in Unresolved Statuses","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"Across AP's dashboard categories, many of Trump's highest-salience immigration and tariff pledges remained in-progress or complicated rather than settled. The pattern suggested structural execution drag in exactly the areas most central to his political brand. That unresolved clustering undercut simplified narratives of total agenda completion.","rationale":"AP tracker pattern showed Trump priorities clustered in unresolved status buckets.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["pattern analysis", "immigration promises", "tariff promises", "unresolved status", "AP dashboard"],"metrics_key":"promise","scores":make_scores("2026-02-28","Conspiracy Theories / Disinformation","Systematic Presidential Lying",6,4,7,5,3,4,8,9,"AP tracker showed Trump's signature policy promises clustered in unresolved status categories.")},
]

entry_cols=["entry_number","title","date_start","date_end","synopsis","rationale","category","subcategory","keywords","age","phase","impressions","reach_estimate","financial_cost_usd","public_reaction","fact_check","fact_check_sources","scores"]
score_cols=["entry_number","insanity","absurdity","danger","authoritarianism","lawlessness","credibility_risk","recency_intensity","impact_scope","rationale_short","rationale_detail"]
source_cols=["entry_number","url","title","publisher","date_published","source_type"]

entry_vals=[]; score_vals=[]; source_vals=[]; keyword_vals=[]
source_title="Tracking Trump's presidential promises"
for e in entries:
    m=metrics[e["metrics_key"]]
    e["impressions"]=m["impressions"]; e["reach_estimate"]=m["reach_estimate"]; e["financial_cost_usd"]=m["financial_cost_usd"]; e["public_reaction"]=m["public_reaction"]; e["age"]=calc_age(e["date_start"])
    s=e["scores"]
    entry_vals.append("("+", ".join([
        str(e["entry_number"]),f"'{sql_escape(e['title'])}'",f"'{e['date_start']}'",f"'{e['date_end']}'",f"'{sql_escape(e['synopsis'])}'",f"'{sql_escape(e['rationale'])}'",f"'{sql_escape(e['category'])}'",f"'{sql_escape(e['subcategory'])}'",arr_sql(e["keywords"]),str(e["age"]),f"'{sql_escape(e['phase'])}'",str(e["impressions"]),str(e["reach_estimate"]),str(e["financial_cost_usd"]),json_sql(e["public_reaction"]),"NULL","ARRAY[]::text[]",json_sql(s)
    ])+")")
    score_vals.append("("+", ".join([
        str(e["entry_number"]),str(s["insanity"]),str(s["absurdity"]),str(s["danger"]),str(s["authoritarianism"]),str(s["lawlessness"]),str(s["credibility_risk"]),str(s["recency_intensity"]),str(s["impact_scope"]),f"'{sql_escape(s['rationale_short'])}'",f"'{sql_escape(s['rationale_detail'])}'"
    ])+")")
    source_vals.append("("+", ".join([
        str(e["entry_number"]),f"'{u}'",f"'{sql_escape(source_title)}'",f"'AP News'",f"'{e['date_start']}'",f"'news'"
    ])+")")
    for kw in e["keywords"]: keyword_vals.append("("+", ".join([str(e["entry_number"]),f"'{sql_escape(kw)}'"])+")")

sql_entries="INSERT INTO public.trump_entries ("+", ".join(entry_cols)+") VALUES\n"+",\n".join(entry_vals)+"\nON CONFLICT DO NOTHING;"
sql_scores="INSERT INTO public.trump_individual_scores ("+", ".join(score_cols)+") VALUES\n"+",\n".join(score_vals)+"\nON CONFLICT DO NOTHING;"
sql_sources="INSERT INTO public.trump_sources ("+", ".join(source_cols)+") VALUES\n"+",\n".join(source_vals)+";"
sql_keywords="INSERT INTO public.trump_keywords (entry_number, keyword) VALUES\n"+",\n".join(keyword_vals)+"\nON CONFLICT DO NOTHING;"
print(json.dumps([sql_entries,sql_scores,sql_sources,sql_keywords],indent=2))
