import json
from datetime import datetime

months = ["Jan.", "Feb.", "Mar.", "Apr.", "May", "Jun.", "Jul.", "Aug.", "Sep.", "Oct.", "Nov.", "Dec."]
birth_date = datetime(1946, 6, 14)


def format_date(date_str: str) -> str:
    d = datetime.strptime(date_str, "%Y-%m-%d")
    return f"{months[d.month - 1]} {d.day}, {d.year}"


def calc_age(date_str: str) -> int:
    d = datetime.strptime(date_str, "%Y-%m-%d")
    age = d.year - birth_date.year
    if (d.month, d.day) < (birth_date.month, birth_date.day):
        age -= 1
    return age


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def json_sql(obj) -> str:
    return "'" + json.dumps(obj, separators=(",", ":"), ensure_ascii=True).replace("'", "''") + "'::jsonb"


def arr_sql(items) -> str:
    if not items:
        return "ARRAY[]::text[]"
    return "ARRAY[" + ",".join("'" + sql_escape(x) + "'" for x in items) + "]::text[]"


def make_scores(
    date_start,
    category,
    subcategory,
    danger,
    lawlessness,
    impact_scope,
    authoritarianism,
    insanity,
    absurdity,
    credibility_risk,
    recency_intensity,
    rationale_short,
):
    return {
        "danger": danger,
        "insanity": insanity,
        "absurdity": absurdity,
        "lawlessness": lawlessness,
        "impact_scope": impact_scope,
        "rationale_short": rationale_short,
        "authoritarianism": authoritarianism,
        "credibility_risk": credibility_risk,
        "rationale_detail": f"{category}: {subcategory}. On {format_date(date_start)}, {rationale_short}",
        "recency_intensity": recency_intensity,
    }


metrics = {
    "immigration": {
        "impressions": 81000000,
        "reach_estimate": 267300000,
        "financial_cost_usd": 118125000,
        "public_reaction": {"negative": 75, "neutral": 18, "positive": 7},
    },
    "disinfo": {
        "impressions": 29400000,
        "reach_estimate": 92904000,
        "financial_cost_usd": 9000000,
        "public_reaction": {"negative": 65, "neutral": 25, "positive": 10},
    },
    "war_medium": {
        "impressions": 180000000,
        "reach_estimate": 594000000,
        "financial_cost_usd": 1200000000,
        "public_reaction": {"negative": 80, "neutral": 15, "positive": 5},
    },
    "war_low": {
        "impressions": 150000000,
        "reach_estimate": 495000000,
        "financial_cost_usd": 900000000,
        "public_reaction": {"negative": 80, "neutral": 15, "positive": 5},
    },
    "econ_high": {
        "impressions": 248000000,
        "reach_estimate": 887840000,
        "financial_cost_usd": 759000000,
        "public_reaction": {"negative": 70, "neutral": 20, "positive": 10},
    },
    "econ_medium": {
        "impressions": 150000000,
        "reach_estimate": 495000000,
        "financial_cost_usd": 420000000,
        "public_reaction": {"negative": 70, "neutral": 20, "positive": 10},
    },
    "econ_low": {
        "impressions": 126000000,
        "reach_estimate": 380520000,
        "financial_cost_usd": 125000000,
        "public_reaction": {"negative": 65, "neutral": 25, "positive": 10},
    },
    "legal_intimidation": {
        "impressions": 32200000,
        "reach_estimate": 101752000,
        "financial_cost_usd": 13300000,
        "public_reaction": {"negative": 70, "neutral": 20, "positive": 10},
    },
    "authoritarian": {
        "impressions": 129600000,
        "reach_estimate": 445824000,
        "financial_cost_usd": 210000000,
        "public_reaction": {"negative": 75, "neutral": 18, "positive": 7},
    },
    "racism": {
        "impressions": 95000000,
        "reach_estimate": 295000000,
        "financial_cost_usd": 50000000,
        "public_reaction": {"negative": 80, "neutral": 15, "positive": 5},
    },
    "extremist": {
        "impressions": 150000000,
        "reach_estimate": 495000000,
        "financial_cost_usd": 100000000,
        "public_reaction": {"negative": 80, "neutral": 15, "positive": 5},
    },
    "grift": {
        "impressions": 95000000,
        "reach_estimate": 250000000,
        "financial_cost_usd": 90000000,
        "public_reaction": {"negative": 70, "neutral": 20, "positive": 10},
    },
    "social": {
        "impressions": 12600000,
        "reach_estimate": 38052000,
        "financial_cost_usd": 3150000,
        "public_reaction": {"negative": 60, "neutral": 30, "positive": 10},
    },
    "personal": {
        "impressions": 12600000,
        "reach_estimate": 38052000,
        "financial_cost_usd": 3150000,
        "public_reaction": {"negative": 55, "neutral": 30, "positive": 15},
    },
    "election": {
        "impressions": 29400000,
        "reach_estimate": 92904000,
        "financial_cost_usd": 9000000,
        "public_reaction": {"negative": 65, "neutral": 25, "positive": 10},
    },
}


entries = [
    {
        "entry_number": 1146,
        "title": "Poll: Most Americans Say ICE Has Gone Too Far",
        "date_start": "2026-02-05",
        "date_end": "2026-02-05",
        "synopsis": "An NPR/PBS News/Marist poll found 65% of Americans said ICE has gone too far after two fatal shootings in Minnesota.",
        "rationale": "The poll showed broad backlash to the administration's immigration crackdown tactics.",
        "category": "Human Rights Violations",
        "subcategory": "Immigration Crackdown",
        "phase": "White House 2",
        "keywords": ["ICE", "immigration enforcement", "Marist poll", "Minnesota shootings", "public backlash"],
        "metrics_key": "immigration",
        "scores": make_scores(
            "2026-02-05",
            "Human Rights Violations",
            "Immigration Crackdown",
            danger=6,
            lawlessness=6,
            impact_scope=6,
            authoritarianism=7,
            insanity=2,
            absurdity=2,
            credibility_risk=2,
            recency_intensity=6,
            rationale_short="Poll found most Americans say ICE has gone too far.",
        ),
        "source": {
            "url": "https://www.npr.org/2026/02/05/nx-s1-5699413/poll-trump-ice-immigration-economy-approval",
            "title": "Poll: Most Americans say ICE has 'gone too far' in immigration enforcement",
            "publisher": "NPR",
            "date_published": "2026-02-05",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1147,
        "title": "Trump Posts Racist Meme of the Obamas, Refuses to Apologize",
        "date_start": "2026-02-06",
        "date_end": "2026-02-06",
        "synopsis": "Trump shared a video depicting the Obamas as apes on Truth Social and later said he did not make a mistake.",
        "rationale": "The post amplified a racist trope from the president's account and he declined to apologize.",
        "category": "Racism / Discrimination",
        "subcategory": "Racial Discrimination",
        "phase": "White House 2",
        "keywords": ["Truth Social", "racist meme", "Obamas", "apology refusal", "White House response"],
        "metrics_key": "racism",
        "scores": make_scores(
            "2026-02-06",
            "Racism / Discrimination",
            "Racial Discrimination",
            danger=5,
            lawlessness=5,
            impact_scope=5,
            authoritarianism=5,
            insanity=3,
            absurdity=2,
            credibility_risk=2,
            recency_intensity=6,
            rationale_short="Trump posted a racist meme of the Obamas and refused to apologize.",
        ),
        "source": {
            "url": "https://www.npr.org/2026/02/06/nx-s1-5704281/trump-posts-racist-meme-of-the-obamas-then-deletes-it",
            "title": "Trump refuses to apologize after posting racist meme of the Obamas",
            "publisher": "NPR",
            "date_published": "2026-02-06",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1148,
        "title": "Trump Says 'Softer Touch' as Immigration Tactics Face Backlash",
        "date_start": "2026-02-06",
        "date_end": "2026-02-06",
        "synopsis": "After backlash over fatal Minnesota shootings, Trump said ICE should use a softer touch and pulled 700 agents.",
        "rationale": "The administration acknowledged political damage from aggressive tactics while continuing the crackdown.",
        "category": "Human Rights Violations",
        "subcategory": "Immigration Crackdown",
        "phase": "White House 2",
        "keywords": ["ICE", "softer touch", "Minnesota", "agent withdrawal", "immigration crackdown"],
        "metrics_key": "immigration",
        "scores": make_scores(
            "2026-02-06",
            "Human Rights Violations",
            "Immigration Crackdown",
            danger=6,
            lawlessness=6,
            impact_scope=6,
            authoritarianism=7,
            insanity=2,
            absurdity=2,
            credibility_risk=2,
            recency_intensity=6,
            rationale_short="Trump said ICE should use a softer touch and pulled 700 agents.",
        ),
        "source": {
            "url": "https://www.npr.org/2026/02/06/nx-s1-5697026/trumps-harsh-immigration-tactics-are-taking-a-political-hit",
            "title": "Trump's harsh immigration tactics are taking a political hit",
            "publisher": "NPR",
            "date_published": "2026-02-06",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1149,
        "title": "NPR: Extremist Rhetoric Overtakes Federal Messaging Under Trump",
        "date_start": "2026-02-16",
        "date_end": "2026-02-16",
        "synopsis": "NPR reported that federal messaging increasingly echoes extremist and white nationalist themes, including DHS recruitment propaganda.",
        "rationale": "Researchers said extremist language has been normalized in government communications.",
        "category": "Racism / Discrimination",
        "subcategory": "White Supremacist Enablement and Nazi Legitimization",
        "phase": "White House 2",
        "keywords": ["DHS", "extremist rhetoric", "white nationalism", "propaganda", "government messaging"],
        "metrics_key": "extremist",
        "scores": make_scores(
            "2026-02-16",
            "Racism / Discrimination",
            "White Supremacist Enablement and Nazi Legitimization",
            danger=7,
            lawlessness=8,
            impact_scope=8,
            authoritarianism=7,
            insanity=3,
            absurdity=2,
            credibility_risk=4,
            recency_intensity=6,
            rationale_short="NPR documented extremist themes in federal messaging and DHS propaganda.",
        ),
        "source": {
            "url": "https://www.npr.org/2026/02/16/nx-s1-5704347/extremist-racist-messaging-trump",
            "title": "Extremist rhetoric and visuals have overtaken government messaging under Trump",
            "publisher": "NPR",
            "date_published": "2026-02-16",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1150,
        "title": "Trump Says His Administration Should Pay Him Billions in Damages",
        "date_start": "2026-02-18",
        "date_end": "2026-02-18",
        "synopsis": "Trump filed claims against the U.S. government and said he should be paid billions in damages, NPR reported.",
        "rationale": "The president sought personal compensation from the government he leads, raising conflict concerns.",
        "category": "Grift / Financial Exploitation",
        "subcategory": "Government Resource Abuse",
        "phase": "White House 2",
        "keywords": ["lawsuit", "damages", "personal compensation", "NPR Politics Podcast", "conflict of interest"],
        "metrics_key": "grift",
        "scores": make_scores(
            "2026-02-18",
            "Grift / Financial Exploitation",
            "Government Resource Abuse",
            danger=6,
            lawlessness=6,
            impact_scope=6,
            authoritarianism=5,
            insanity=2,
            absurdity=2,
            credibility_risk=6,
            recency_intensity=6,
            rationale_short="Trump said his administration should pay him billions in damages.",
        ),
        "source": {
            "url": "https://www.npr.org/2026/02/18/nx-s1-5717194/trump-says-his-administration-should-pay-him-billions-of-dollars",
            "title": "Trump says his administration should pay him billions of dollars",
            "publisher": "NPR",
            "date_published": "2026-02-18",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1151,
        "title": "Trump Sets 10-15 Day Deadline for Iran Deal, Floats Limited Strikes",
        "date_start": "2026-02-20",
        "date_end": "2026-02-20",
        "synopsis": "Trump said he was considering limited military strikes and gave Iran 10-15 days to reach a nuclear deal.",
        "rationale": "The ultimatum escalated toward military action without public consensus or congressional authorization.",
        "category": "National Security Violations",
        "subcategory": "War / Militarization",
        "phase": "White House 2",
        "keywords": ["Iran", "deadline", "limited strikes", "nuclear talks", "military buildup"],
        "metrics_key": "war_medium",
        "scores": make_scores(
            "2026-02-20",
            "National Security Violations",
            "War / Militarization",
            danger=8,
            lawlessness=6,
            impact_scope=7,
            authoritarianism=5,
            insanity=3,
            absurdity=2,
            credibility_risk=3,
            recency_intensity=8,
            rationale_short="Trump set a 10-15 day deadline and said he was considering limited strikes on Iran.",
        ),
        "source": {
            "url": "https://www.reuters.com/world/middle-east/us-not-seeking-zero-enrichment-talks-irans-foreign-minister-says-2026-02-20/",
            "title": "Iran prepares counterproposal as Trump weighs strikes",
            "publisher": "Reuters",
            "date_published": "2026-02-20",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1152,
        "title": "Trump Claims 32,000 Protesters Killed in Iran, Citing Disputed Figures",
        "date_start": "2026-02-20",
        "date_end": "2026-02-20",
        "synopsis": "Trump said 32,000 people were killed in Iran's unrest and claimed his threats stopped mass hangings; monitors reported far lower verified totals.",
        "rationale": "The president used disputed casualty claims to justify threats of force.",
        "category": "Conspiracy Theories / Disinformation",
        "subcategory": "Systematic Presidential Lying",
        "phase": "White House 2",
        "keywords": ["Iran protests", "casualty claim", "HRANA", "hangings", "disputed figures"],
        "metrics_key": "disinfo",
        "scores": make_scores(
            "2026-02-20",
            "Conspiracy Theories / Disinformation",
            "Systematic Presidential Lying",
            danger=3,
            lawlessness=2,
            impact_scope=4,
            authoritarianism=3,
            insanity=2,
            absurdity=3,
            credibility_risk=7,
            recency_intensity=6,
            rationale_short="Trump claimed 32,000 killed in Iran and said his threats stopped hangings.",
        ),
        "source": {
            "url": "https://www.reuters.com/world/middle-east/us-not-seeking-zero-enrichment-talks-irans-foreign-minister-says-2026-02-20/",
            "title": "Iran prepares counterproposal as Trump weighs strikes",
            "publisher": "Reuters",
            "date_published": "2026-02-20",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1153,
        "title": "U.S. Military Buildup Puts Iran Talks on Collision Course",
        "date_start": "2026-02-20",
        "date_end": "2026-02-20",
        "synopsis": "Reuters reported the U.S. and Iran were sliding toward conflict as Trump ordered a major military buildup in the region.",
        "rationale": "The escalation increased risks of war while diplomacy stalled.",
        "category": "National Security Violations",
        "subcategory": "War / Militarization",
        "phase": "White House 2",
        "keywords": ["military buildup", "Middle East", "Iran talks", "war risk", "U.S. deployment"],
        "metrics_key": "war_medium",
        "scores": make_scores(
            "2026-02-20",
            "National Security Violations",
            "War / Militarization",
            danger=7,
            lawlessness=5,
            impact_scope=7,
            authoritarianism=5,
            insanity=3,
            absurdity=2,
            credibility_risk=3,
            recency_intensity=8,
            rationale_short="Trump ordered a major military buildup as Iran talks stalled.",
        ),
        "source": {
            "url": "https://www.reuters.com/world/middle-east/us-iran-slide-towards-conflict-military-buildup-eclipses-talks-2026-02-20/",
            "title": "US and Iran slide towards conflict as military buildup eclipses talks",
            "publisher": "Reuters",
            "date_published": "2026-02-20",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1154,
        "title": "Trump Blames Shutdown for GDP Slowdown, Demands Lower Rates Online",
        "date_start": "2026-02-20",
        "date_end": "2026-02-20",
        "synopsis": "After GDP slowed, Trump posted that the shutdown cost two points of growth and called for lower interest rates.",
        "rationale": "The president used social media to pressure monetary policy amid economic volatility.",
        "category": "Social Media",
        "subcategory": "Communication Chaos",
        "phase": "White House 2",
        "keywords": ["GDP", "shutdown", "interest rates", "social media post", "Federal Reserve"],
        "metrics_key": "social",
        "scores": make_scores(
            "2026-02-20",
            "Social Media",
            "Communication Chaos",
            danger=4,
            lawlessness=2,
            impact_scope=4,
            authoritarianism=3,
            insanity=2,
            absurdity=3,
            credibility_risk=2,
            recency_intensity=6,
            rationale_short="Trump blamed the shutdown for GDP slowdown and demanded lower rates.",
        ),
        "source": {
            "url": "https://www.reuters.com/world/us/us-economic-growth-slows-sharply-fourth-quarter-2026-02-20/",
            "title": "Government shutdown dents US economic growth in fourth quarter; inflation heats up",
            "publisher": "Reuters",
            "date_published": "2026-02-20",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1155,
        "title": "Trump Raises Global Tariff to 15% After Supreme Court Ruling",
        "date_start": "2026-02-21",
        "date_end": "2026-02-21",
        "synopsis": "Trump announced a 15% temporary global tariff under Section 122 after the Supreme Court struck down his prior program.",
        "rationale": "He escalated a trade war using a new legal workaround after a judicial rebuke.",
        "category": "Foreign Policy",
        "subcategory": "Economic Warfare",
        "phase": "White House 2",
        "keywords": ["tariffs", "Section 122", "Supreme Court ruling", "trade war", "global levy"],
        "metrics_key": "econ_high",
        "scores": make_scores(
            "2026-02-21",
            "Foreign Policy",
            "Economic Warfare",
            danger=7,
            lawlessness=5,
            impact_scope=8,
            authoritarianism=6,
            insanity=2,
            absurdity=2,
            credibility_risk=4,
            recency_intensity=7,
            rationale_short="Trump raised the global tariff rate to 15% after the court ruling.",
        ),
        "source": {
            "url": "https://www.reuters.com/world/us/trump-says-he-will-raise-global-tariff-rate-10-15-2026-02-21/",
            "title": "After court ruling, Trump says US global tariff rate will rise from 10% to 15%",
            "publisher": "Reuters",
            "date_published": "2026-02-21",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1156,
        "title": "Trump Calls Supreme Court Justices 'Fools' After Tariff Ruling",
        "date_start": "2026-02-21",
        "date_end": "2026-02-21",
        "synopsis": "After the tariff ruling, Trump denounced Supreme Court justices as fools and embarrassments, Reuters reported.",
        "rationale": "Public attacks on the judiciary undercut institutional checks on presidential power.",
        "category": "Government Corruption",
        "subcategory": "Legal Intimidation",
        "phase": "White House 2",
        "keywords": ["Supreme Court", "justices", "tariff ruling", "judiciary attacks", "legal intimidation"],
        "metrics_key": "legal_intimidation",
        "scores": make_scores(
            "2026-02-21",
            "Government Corruption",
            "Legal Intimidation",
            danger=5,
            lawlessness=5,
            impact_scope=5,
            authoritarianism=5,
            insanity=2,
            absurdity=2,
            credibility_risk=2,
            recency_intensity=6,
            rationale_short="Trump attacked Supreme Court justices as fools after the tariff ruling.",
        ),
        "source": {
            "url": "https://www.reuters.com/world/us/trump-says-he-will-raise-global-tariff-rate-10-15-2026-02-21/",
            "title": "After court ruling, Trump says US global tariff rate will rise from 10% to 15%",
            "publisher": "Reuters",
            "date_published": "2026-02-21",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1157,
        "title": "U.S. Trade Chief Says Tariff Deals Stand Despite Court Ruling",
        "date_start": "2026-02-22",
        "date_end": "2026-02-22",
        "synopsis": "USTR Jamieson Greer said partner countries were not pulling out of tariff deals after the Supreme Court ruling.",
        "rationale": "The administration pressed forward with contentious trade agreements despite legal uncertainty.",
        "category": "Foreign Policy",
        "subcategory": "Economic Warfare",
        "phase": "White House 2",
        "keywords": ["USTR", "tariff deals", "trade partners", "court ruling", "Greer"],
        "metrics_key": "econ_low",
        "scores": make_scores(
            "2026-02-22",
            "Foreign Policy",
            "Economic Warfare",
            danger=6,
            lawlessness=5,
            impact_scope=7,
            authoritarianism=5,
            insanity=2,
            absurdity=2,
            credibility_risk=4,
            recency_intensity=6,
            rationale_short="USTR said tariff deals remained in force after the court ruling.",
        ),
        "source": {
            "url": "https://www.reuters.com/world/us/us-trade-chief-says-no-countries-have-said-they-will-withdraw-tariff-deals-2026-02-22/",
            "title": "US trade chief says not seeing countries move to pull out of tariff deals",
            "publisher": "Reuters",
            "date_published": "2026-02-22",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1158,
        "title": "Tariff Whiplash Returns, Leaving Trade Rules in Flux",
        "date_start": "2026-02-23",
        "date_end": "2026-02-23",
        "synopsis": "Reuters reported renewed uncertainty as Trump shifted tariff plans after the court ruling, clouding business decisions.",
        "rationale": "Rapid policy reversals destabilized trade planning and investment.",
        "category": "Foreign Policy",
        "subcategory": "Economic Warfare",
        "phase": "White House 2",
        "keywords": ["tariff uncertainty", "business planning", "trade policy", "court ruling", "economic fog"],
        "metrics_key": "econ_medium",
        "scores": make_scores(
            "2026-02-23",
            "Foreign Policy",
            "Economic Warfare",
            danger=6,
            lawlessness=5,
            impact_scope=7,
            authoritarianism=5,
            insanity=2,
            absurdity=2,
            credibility_risk=4,
            recency_intensity=6,
            rationale_short="Tariff reversals renewed uncertainty for trade policy and business planning.",
        ),
        "source": {
            "url": "https://www.reuters.com/business/with-us-tariff-rates-up-air-economic-fog-again-thickens-2026-02-23/",
            "title": "With US tariff rates up in the air, the economic fog again thickens",
            "publisher": "Reuters",
            "date_published": "2026-02-23",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1159,
        "title": "Immigration Courts Lose a Quarter of Judges After Trump Firings",
        "date_start": "2026-02-23",
        "date_end": "2026-02-23",
        "synopsis": "NPR reported the immigration court system has about 25% fewer judges after widespread firings and resignations.",
        "rationale": "The purge weakened due process capacity amid mass deportation efforts.",
        "category": "Human Rights Violations",
        "subcategory": "Immigration Crackdown",
        "phase": "White House 2",
        "keywords": ["immigration judges", "EOIR", "court backlogs", "firings", "due process"],
        "metrics_key": "immigration",
        "scores": make_scores(
            "2026-02-23",
            "Human Rights Violations",
            "Immigration Crackdown",
            danger=7,
            lawlessness=7,
            impact_scope=7,
            authoritarianism=8,
            insanity=2,
            absurdity=2,
            credibility_risk=3,
            recency_intensity=6,
            rationale_short="Immigration courts lost roughly a quarter of judges after firings.",
        ),
        "source": {
            "url": "https://www.npr.org/2026/02/23/g-s1-110911/trump-immigration-judges-dismissals-numbers",
            "title": "U.S. has a quarter fewer immigration judges than it did a year ago. Here's why",
            "publisher": "NPR",
            "date_published": "2026-02-23",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1160,
        "title": "Trump Declares 'Golden Age' in SOTU Despite Low Approval",
        "date_start": "2026-02-24",
        "date_end": "2026-02-24",
        "synopsis": "In his State of the Union, Trump said the nation was in a golden age and touted economic gains while polls showed discontent.",
        "rationale": "The speech presented a sharply upbeat narrative at odds with public sentiment.",
        "category": "Conspiracy Theories / Disinformation",
        "subcategory": "Systematic Presidential Lying",
        "phase": "White House 2",
        "keywords": ["State of the Union", "golden age", "economy", "approval ratings", "cost of living"],
        "metrics_key": "disinfo",
        "scores": make_scores(
            "2026-02-24",
            "Conspiracy Theories / Disinformation",
            "Systematic Presidential Lying",
            danger=3,
            lawlessness=2,
            impact_scope=4,
            authoritarianism=3,
            insanity=2,
            absurdity=3,
            credibility_risk=6,
            recency_intensity=6,
            rationale_short="Trump declared a golden age in his State of the Union despite low approval.",
        ),
        "source": {
            "url": "https://reuters.com/world/us/trump-facing-headwinds-home-abroad-address-state-union-2026-02-24/",
            "title": "Trump hails 'golden age' in State of the Union as voters sour on economy",
            "publisher": "Reuters",
            "date_published": "2026-02-24",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1161,
        "title": "Trump Uses SOTU to Justify Possible Iran Attack",
        "date_start": "2026-02-24",
        "date_end": "2026-02-24",
        "synopsis": "Trump said he would not allow Iran to obtain a nuclear weapon and cited terrorism and missiles to justify potential strikes.",
        "rationale": "He framed a case for war without detailed public evidence.",
        "category": "National Security Violations",
        "subcategory": "War / Militarization",
        "phase": "White House 2",
        "keywords": ["Iran", "State of the Union", "nuclear weapons", "terrorism", "military action"],
        "metrics_key": "war_medium",
        "scores": make_scores(
            "2026-02-24",
            "National Security Violations",
            "War / Militarization",
            danger=7,
            lawlessness=5,
            impact_scope=7,
            authoritarianism=5,
            insanity=3,
            absurdity=2,
            credibility_risk=3,
            recency_intensity=8,
            rationale_short="Trump used the SOTU to justify possible strikes on Iran.",
        ),
        "source": {
            "url": "https://www.reuters.com/world/us/state-union-could-be-trumps-best-chance-sell-voters-iran-plans-2026-02-24/",
            "title": "Trump briefly lays out case for possible attack on Iran in State of the Union",
            "publisher": "Reuters",
            "date_published": "2026-02-24",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1162,
        "title": "Reuters/Ipsos Poll: Most Americans Say Trump Is Growing Erratic",
        "date_start": "2026-02-24",
        "date_end": "2026-02-24",
        "synopsis": "A Reuters/Ipsos poll found 61% of Americans view Trump as growing erratic as he ages.",
        "rationale": "The poll underscored concerns about stability in presidential decision-making.",
        "category": "Personal Awareness",
        "subcategory": "Public Gaffe",
        "phase": "White House 2",
        "keywords": ["Reuters/Ipsos", "poll", "erratic", "age", "public perception"],
        "metrics_key": "personal",
        "scores": make_scores(
            "2026-02-24",
            "Personal Awareness",
            "Public Gaffe",
            danger=2,
            lawlessness=1,
            impact_scope=3,
            authoritarianism=1,
            insanity=2,
            absurdity=2,
            credibility_risk=2,
            recency_intensity=6,
            rationale_short="A Reuters/Ipsos poll found most Americans view Trump as erratic with age.",
        ),
        "source": {
            "url": "https://www.reuters.com/world/us/most-americans-say-trump-is-growing-erratic-with-age-reutersipsos-poll-finds-2026-02-24/",
            "title": "Most Americans say Trump is growing erratic with age, Reuters/Ipsos poll finds",
            "publisher": "Reuters",
            "date_published": "2026-02-24",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1163,
        "title": "Trump Touts Peace Record and Suggests Nobel Prize Despite Unresolved Conflicts",
        "date_start": "2026-02-24",
        "date_end": "2026-02-24",
        "synopsis": "Trump claimed he had solved multiple wars and should receive the Nobel Peace Prize, though Reuters noted conflicts remain unresolved.",
        "rationale": "The self-praise contradicted on-the-ground outcomes and inflated achievements.",
        "category": "Conspiracy Theories / Disinformation",
        "subcategory": "Systematic Presidential Lying",
        "phase": "White House 2",
        "keywords": ["Nobel Peace Prize", "diplomatic record", "wars", "self-praise", "unresolved conflicts"],
        "metrics_key": "disinfo",
        "scores": make_scores(
            "2026-02-24",
            "Conspiracy Theories / Disinformation",
            "Systematic Presidential Lying",
            danger=3,
            lawlessness=2,
            impact_scope=4,
            authoritarianism=3,
            insanity=2,
            absurdity=3,
            credibility_risk=6,
            recency_intensity=6,
            rationale_short="Trump claimed he solved wars and suggested he deserved a Nobel.",
        ),
        "source": {
            "url": "https://www.reuters.com/world/asia-pacific/trump-touts-his-diplomatic-record-results-are-mixed-2026-02-24/",
            "title": "Trump says he has solved many wars. Has he?",
            "publisher": "Reuters",
            "date_published": "2026-02-24",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1164,
        "title": "Poll: Checks and Balances Not Working Under Trump, Majority Says",
        "date_start": "2026-02-23",
        "date_end": "2026-02-23",
        "synopsis": "A PBS News/NPR/Marist poll found two-thirds of Americans say checks and balances are not working well.",
        "rationale": "The poll reflected growing concern about concentration of executive power.",
        "category": "Authoritarianism",
        "subcategory": "Government Power Abuse",
        "phase": "White House 2",
        "keywords": ["checks and balances", "Marist poll", "executive power", "Congress", "courts"],
        "metrics_key": "authoritarian",
        "scores": make_scores(
            "2026-02-23",
            "Authoritarianism",
            "Government Power Abuse",
            danger=6,
            lawlessness=7,
            impact_scope=7,
            authoritarianism=8,
            insanity=2,
            absurdity=2,
            credibility_risk=4,
            recency_intensity=6,
            rationale_short="A Marist poll found checks and balances were not working well under Trump.",
        ),
        "source": {
            "url": "https://www.pbs.org/newshour/politics/checks-and-balances-arent-working-under-trump-growing-majority-says",
            "title": "Checks and balances aren't working under Trump, growing majority says",
            "publisher": "PBS News",
            "date_published": "2026-02-23",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1165,
        "title": "PBS: Trump Warns Iran of 'Bad Things' as Foreign Policy Case Looms",
        "date_start": "2026-02-24",
        "date_end": "2026-02-24",
        "synopsis": "PBS reported Trump warned Iran of bad things if no deal and prepared to justify his foreign policy priorities.",
        "rationale": "The administration signaled readiness to escalate militarily amid public unease.",
        "category": "National Security Violations",
        "subcategory": "War / Militarization",
        "phase": "White House 2",
        "keywords": ["Iran warning", "foreign policy", "State of the Union", "military action", "public unease"],
        "metrics_key": "war_low",
        "scores": make_scores(
            "2026-02-24",
            "National Security Violations",
            "War / Militarization",
            danger=6,
            lawlessness=4,
            impact_scope=6,
            authoritarianism=4,
            insanity=2,
            absurdity=2,
            credibility_risk=3,
            recency_intensity=7,
            rationale_short="Trump warned Iran of bad things and signaled readiness to escalate.",
        ),
        "source": {
            "url": "https://www.pbs.org/newshour/politics/state-of-the-union-offers-trump-a-chance-to-make-the-case-for-his-foreign-policy-approach",
            "title": "State of the Union offers Trump a chance to make the case for his foreign policy approach",
            "publisher": "PBS News",
            "date_published": "2026-02-24",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1166,
        "title": "Trump Urges SAVE America Act Requiring Proof of Citizenship to Vote",
        "date_start": "2026-02-25",
        "date_end": "2026-02-25",
        "synopsis": "Trump asked Congress to pass the SAVE America Act to require proof of citizenship for voting.",
        "rationale": "The proposal would tighten voting access based on election-fraud claims.",
        "category": "Election Interference",
        "subcategory": "Election Interference",
        "phase": "White House 2",
        "keywords": ["SAVE America Act", "proof of citizenship", "voting", "election fraud claims", "State of the Union"],
        "metrics_key": "election",
        "scores": make_scores(
            "2026-02-25",
            "Election Interference",
            "Election Interference",
            danger=4,
            lawlessness=7,
            impact_scope=4,
            authoritarianism=3,
            insanity=2,
            absurdity=2,
            credibility_risk=2,
            recency_intensity=6,
            rationale_short="Trump urged passage of the SAVE America Act requiring proof of citizenship to vote.",
        ),
        "source": {
            "url": "https://www.npr.org/2026/02/25/nx-s1-5717096/trump-congress-state-union-highlights",
            "title": "5 takeaways from Trump's State of the Union address",
            "publisher": "NPR",
            "date_published": "2026-02-25",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1167,
        "title": "Trump Pushes 'Delilah Law' to Bar Commercial Licenses for Undocumented Immigrants",
        "date_start": "2026-02-25",
        "date_end": "2026-02-25",
        "synopsis": "Trump asked Congress to pass the Delilah Law banning commercial licenses for undocumented immigrants.",
        "rationale": "The proposal tightened restrictions as part of the immigration crackdown.",
        "category": "Human Rights Violations",
        "subcategory": "Immigration Crackdown",
        "phase": "White House 2",
        "keywords": ["Delilah Law", "commercial licenses", "undocumented immigrants", "immigration policy", "State of the Union"],
        "metrics_key": "immigration",
        "scores": make_scores(
            "2026-02-25",
            "Human Rights Violations",
            "Immigration Crackdown",
            danger=6,
            lawlessness=6,
            impact_scope=6,
            authoritarianism=7,
            insanity=2,
            absurdity=2,
            credibility_risk=2,
            recency_intensity=6,
            rationale_short="Trump pushed the Delilah Law to bar commercial licenses for undocumented immigrants.",
        ),
        "source": {
            "url": "https://www.npr.org/2026/02/25/nx-s1-5717096/trump-congress-state-union-highlights",
            "title": "5 takeaways from Trump's State of the Union address",
            "publisher": "NPR",
            "date_published": "2026-02-25",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1168,
        "title": "Trump Defies Supreme Court on Tariffs, Claims Alternate Legal Authority",
        "date_start": "2026-02-25",
        "date_end": "2026-02-25",
        "synopsis": "NPR reported Trump criticized the Court's tariff ruling and said he had alternate legal justifications to keep tariffs in place.",
        "rationale": "He signaled continued defiance of judicial limits on executive trade power.",
        "category": "Authoritarianism",
        "subcategory": "Government Power Abuse",
        "phase": "White House 2",
        "keywords": ["tariffs", "Supreme Court", "alternative legal authority", "State of the Union", "executive power"],
        "metrics_key": "authoritarian",
        "scores": make_scores(
            "2026-02-25",
            "Authoritarianism",
            "Government Power Abuse",
            danger=6,
            lawlessness=7,
            impact_scope=7,
            authoritarianism=8,
            insanity=2,
            absurdity=2,
            credibility_risk=4,
            recency_intensity=6,
            rationale_short="Trump said he had alternate legal authority to keep tariffs in place.",
        ),
        "source": {
            "url": "https://www.npr.org/2026/02/25/nx-s1-5717096/trump-congress-state-union-highlights",
            "title": "5 takeaways from Trump's State of the Union address",
            "publisher": "NPR",
            "date_published": "2026-02-25",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1169,
        "title": "Tariff Turmoil Leaves Treasury Markets Dazed After Court Ruling",
        "date_start": "2026-02-23",
        "date_end": "2026-02-23",
        "synopsis": "Reuters reported market uncertainty and fiscal risks after the court struck down tariffs and Trump rushed replacement levies.",
        "rationale": "The policy whiplash destabilized markets and raised deficit concerns.",
        "category": "Foreign Policy",
        "subcategory": "Economic Warfare",
        "phase": "White House 2",
        "keywords": ["Treasury markets", "tariff turmoil", "refunds", "trade policy", "market volatility"],
        "metrics_key": "econ_medium",
        "scores": make_scores(
            "2026-02-23",
            "Foreign Policy",
            "Economic Warfare",
            danger=6,
            lawlessness=5,
            impact_scope=7,
            authoritarianism=5,
            insanity=2,
            absurdity=2,
            credibility_risk=4,
            recency_intensity=6,
            rationale_short="Tariff turmoil and replacement levies rattled Treasury markets.",
        ),
        "source": {
            "url": "https://www.reuters.com/business/retail-consumer/us-tariff-turmoil-leaves-treasury-markets-dazed-2026-02-23/",
            "title": "US tariff turmoil leaves Treasury markets dazed",
            "publisher": "Reuters",
            "date_published": "2026-02-23",
            "source_type": "news",
        },
    },
    {
        "entry_number": 1170,
        "title": "Global Reaction Mounts as Trump Issues New Tariff Threats",
        "date_start": "2026-02-23",
        "date_end": "2026-02-23",
        "synopsis": "Reuters compiled reactions after Trump threatened new tariffs following the Supreme Court ruling, with EU and others demanding clarity.",
        "rationale": "The threat escalated international trade tensions after a legal rebuke.",
        "category": "Foreign Policy",
        "subcategory": "Economic Warfare",
        "phase": "White House 2",
        "keywords": ["tariff threat", "Supreme Court ruling", "EU reaction", "trade tensions", "international response"],
        "metrics_key": "econ_low",
        "scores": make_scores(
            "2026-02-23",
            "Foreign Policy",
            "Economic Warfare",
            danger=6,
            lawlessness=5,
            impact_scope=7,
            authoritarianism=5,
            insanity=2,
            absurdity=2,
            credibility_risk=4,
            recency_intensity=6,
            rationale_short="Global leaders reacted to Trump's new tariff threat after the court ruling.",
        ),
        "source": {
            "url": "https://www.reuters.com/business/finance/reaction-us-supreme-court-ruling-trumps-new-tariff-threat-2026-02-23/",
            "title": "Reaction to US Supreme Court ruling and Trump's new tariff threat",
            "publisher": "Reuters",
            "date_published": "2026-02-23",
            "source_type": "news",
        },
    },
]

# apply metrics and age
for e in entries:
    m = metrics[e["metrics_key"]]
    e["impressions"] = m["impressions"]
    e["reach_estimate"] = m["reach_estimate"]
    e["financial_cost_usd"] = m["financial_cost_usd"]
    e["public_reaction"] = m["public_reaction"]
    e["age"] = calc_age(e["date_start"])

entry_columns = [
    "entry_number",
    "title",
    "date_start",
    "date_end",
    "synopsis",
    "rationale",
    "category",
    "subcategory",
    "keywords",
    "age",
    "phase",
    "impressions",
    "reach_estimate",
    "financial_cost_usd",
    "public_reaction",
    "fact_check",
    "fact_check_sources",
    "scores",
]

score_columns = [
    "entry_number",
    "insanity",
    "absurdity",
    "danger",
    "authoritarianism",
    "lawlessness",
    "credibility_risk",
    "recency_intensity",
    "impact_scope",
    "rationale_short",
    "rationale_detail",
]

source_columns = ["entry_number", "url", "title", "publisher", "date_published", "source_type"]

entry_values = []
score_values = []
source_values = []
keyword_values = []

for e in entries:
    scores = e["scores"]
    entry_values.append(
        "("
        + ", ".join(
            [
                str(e["entry_number"]),
                f"'{sql_escape(e['title'])}'",
                f"'{e['date_start']}'",
                f"'{e['date_end']}'",
                f"'{sql_escape(e['synopsis'])}'",
                f"'{sql_escape(e['rationale'])}'",
                f"'{sql_escape(e['category'])}'",
                f"'{sql_escape(e['subcategory'])}'",
                arr_sql(e["keywords"]),
                str(e["age"]),
                f"'{sql_escape(e['phase'])}'",
                str(e["impressions"]),
                str(e["reach_estimate"]),
                str(e["financial_cost_usd"]),
                json_sql(e["public_reaction"]),
                "NULL",
                "ARRAY[]::text[]",
                json_sql(scores),
            ]
        )
        + ")"
    )

    score_values.append(
        "("
        + ", ".join(
            [
                str(e["entry_number"]),
                str(scores["insanity"]),
                str(scores["absurdity"]),
                str(scores["danger"]),
                str(scores["authoritarianism"]),
                str(scores["lawlessness"]),
                str(scores["credibility_risk"]),
                str(scores["recency_intensity"]),
                str(scores["impact_scope"]),
                f"'{sql_escape(scores['rationale_short'])}'",
                f"'{sql_escape(scores['rationale_detail'])}'",
            ]
        )
        + ")"
    )

    src = e["source"]
    source_values.append(
        "("
        + ", ".join(
            [
                str(e["entry_number"]),
                f"'{sql_escape(src['url'])}'",
                f"'{sql_escape(src['title'])}'",
                f"'{sql_escape(src['publisher'])}'",
                f"'{src['date_published']}'",
                f"'{sql_escape(src['source_type'])}'",
            ]
        )
        + ")"
    )

    for kw in e["keywords"]:
        keyword_values.append(
            "("
            + ", ".join(
                [
                    str(e["entry_number"]),
                    f"'{sql_escape(kw)}'",
                ]
            )
            + ")"
        )

sql_entries = (
    "INSERT INTO public.trump_entries ("
    + ", ".join(entry_columns)
    + ") VALUES\n"
    + ",\n".join(entry_values)
    + "\nON CONFLICT DO NOTHING;"
)

sql_scores = (
    "INSERT INTO public.trump_individual_scores ("
    + ", ".join(score_columns)
    + ") VALUES\n"
    + ",\n".join(score_values)
    + "\nON CONFLICT DO NOTHING;"
)

sql_sources = (
    "INSERT INTO public.trump_sources ("
    + ", ".join(source_columns)
    + ") VALUES\n"
    + ",\n".join(source_values)
    + ";"
)

sql_keywords = (
    "INSERT INTO public.trump_keywords (entry_number, keyword) VALUES\n"
    + ",\n".join(keyword_values)
    + "\nON CONFLICT DO NOTHING;"
)

sql_statements = [sql_entries, sql_scores, sql_sources, sql_keywords]

print(json.dumps(sql_statements, indent=2))
