import json
from datetime import datetime

months=["Jan.","Feb.","Mar.","Apr.","May","Jun.","Jul.","Aug.","Sep.","Oct.","Nov.","Dec."]
birth_date=datetime(1946,6,14)

def format_date(date_str:str)->str:
    d=datetime.strptime(date_str,"%Y-%m-%d")
    return f"{months[d.month-1]} {d.day}, {d.year}"

def calc_age(date_str:str)->int:
    d=datetime.strptime(date_str,"%Y-%m-%d")
    a=d.year-birth_date.year
    if (d.month,d.day)<(birth_date.month,birth_date.day): a-=1
    return a

def sql_escape(v:str)->str: return v.replace("'","''")
def json_sql(o)->str: return "'"+json.dumps(o,separators=(",",":"),ensure_ascii=True).replace("'","''")+"'::jsonb"
def arr_sql(items)->str:
    if not items: return "ARRAY[]::text[]"
    return "ARRAY["+",".join("'"+sql_escape(x)+"'" for x in items)+"]::text[]"

def make_scores(date_start,category,subcategory,danger,lawlessness,impact_scope,authoritarianism,insanity,absurdity,credibility_risk,recency_intensity,rationale_short):
    return {
        "danger":danger,"insanity":insanity,"absurdity":absurdity,"lawlessness":lawlessness,"impact_scope":impact_scope,
        "rationale_short":rationale_short,"authoritarianism":authoritarianism,"credibility_risk":credibility_risk,
        "rationale_detail":f"{category}: {subcategory}. On {format_date(date_start)}, {rationale_short}","recency_intensity":recency_intensity,
    }

metrics={
    "war":{"impressions":198000000,"reach_estimate":691000000,"financial_cost_usd":1180000000,"public_reaction":{"negative":80,"neutral":14,"positive":6}},
    "diplomacy":{"impressions":170000000,"reach_estimate":579000000,"financial_cost_usd":540000000,"public_reaction":{"negative":76,"neutral":17,"positive":7}},
    "governance":{"impressions":157000000,"reach_estimate":536000000,"financial_cost_usd":330000000,"public_reaction":{"negative":77,"neutral":16,"positive":7}},
}

entries=[
{ "entry_number":1346,"title":"Trump Oversaw a War Phase Where Iranian State Media Reported Khamenei's Death After Joint Strikes","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP reported Iranian state media said Supreme Leader Ali Khamenei had been killed in a major U.S.-Israeli attack wave. Even with competing verification channels, the headline signaled the conflict had crossed into regime-shaking territory under Trump's watch. The event dramatically expanded geopolitical risk and the stakes of every subsequent statement from Washington.","rationale":"AP reported state-media confirmation of Khamenei's death during Trump-era escalation.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["Khamenei death","state media claim","joint strikes","regime shock","escalation"],"metrics_key":"war","source_url":"https://apnews.com/article/c2f11247d8a66e36929266f2c557a54c","source_title":"Iran's supreme leader killed in major attack by US and Israel","source_publisher":"AP News","scores":make_scores("2026-02-28","Foreign Policy","Military Escalation",9,7,10,6,3,3,8,10,"A regime-level shock headline emerged during Trump's escalation timeline.")},
{ "entry_number":1347,"title":"Trump's Iran Strategy Entered a Succession-Crisis Zone With Global Security Consequences","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"By AP's account, the reported death of Iran's top leader triggered immediate succession and command-control uncertainty. That kind of vacuum can increase miscalculation risk across proxies, missile forces and diplomatic channels. Under Trump's policy arc, the conflict moved from pressure campaign framing to leadership-decapitation consequences.","rationale":"AP's reporting implied succession instability after a leader-targeting war phase under Trump.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["succession risk","command uncertainty","miscalculation","leadership decapitation","regional fallout"],"metrics_key":"war","source_url":"https://apnews.com/article/c2f11247d8a66e36929266f2c557a54c","source_title":"Iran's supreme leader killed in major attack by US and Israel","source_publisher":"AP News","scores":make_scores("2026-02-28","Foreign Policy","Military Escalation",9,7,10,6,3,3,8,10,"Trump's war posture was linked to potential succession instability in Iran.")},
{ "entry_number":1348,"title":"Trump's Escalation Narrative Faced New Legitimacy Questions After Regime-Level Shock Reports","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's coverage turned the debate from tactical objectives to strategic legitimacy: if outcomes look regime-toppling, prior claims of bounded intent become harder to defend. Under Trump's communication style, those inconsistencies fed domestic and international skepticism. The conflict looked less controlled than advertised.","rationale":"AP reporting increased skepticism about bounded-war claims in Trump's Iran messaging.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["bounded intent","regime shock","legitimacy questions","message inconsistency","credibility"],"metrics_key":"war","source_url":"https://apnews.com/article/c2f11247d8a66e36929266f2c557a54c","source_title":"Iran's supreme leader killed in major attack by US and Israel","source_publisher":"AP News","scores":make_scores("2026-02-28","Conspiracy Theories / Disinformation","Systematic Presidential Lying",8,6,9,6,4,4,8,10,"Trump's bounded-war messaging clashed with regime-level shock outcomes.")},
{ "entry_number":1349,"title":"Trump's Iran Campaign Increased Risk of Long-Tail Retaliation Across the Region","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's major-attack reporting implied retaliation pathways could broaden after such a high-impact strike phase. In these scenarios, immediate tactical gains can produce prolonged asymmetric backlash. Trump's escalation therefore raised not only short-term confrontation risk but also medium-term regional security drag.","rationale":"AP context showed heightened retaliation pathways after high-impact strike outcomes.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["retaliation risk","asymmetric backlash","regional drag","high-impact strikes","security pathway"],"metrics_key":"war","source_url":"https://apnews.com/article/c2f11247d8a66e36929266f2c557a54c","source_title":"Iran's supreme leader killed in major attack by US and Israel","source_publisher":"AP News","scores":make_scores("2026-02-28","Foreign Policy","Military Escalation",9,7,9,6,3,3,7,10,"Trump's strike timeline increased the likelihood of prolonged retaliation cycles.")},
{ "entry_number":1350,"title":"Trump's Wartime Messaging Had to Manage a Crisis Bigger Than His Original Public Framing","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"Once AP reported regime-level consequences, Trump's communications challenge changed from selling an operation to managing strategic shock. His usual dominance-through-message approach faced harder limits when events outpaced narrative control. The gap between rhetoric and battlefield consequence became politically costly.","rationale":"AP reporting forced Trump's messaging from sales mode into shock-containment mode.","category":"Authoritarianism","subcategory":"Government Power Abuse","phase":"White House 2","keywords":["shock containment","message limits","battlefield consequences","narrative control","political cost"],"metrics_key":"war","source_url":"https://apnews.com/article/c2f11247d8a66e36929266f2c557a54c","source_title":"Iran's supreme leader killed in major attack by US and Israel","source_publisher":"AP News","scores":make_scores("2026-02-28","Authoritarianism","Government Power Abuse",8,6,9,7,3,3,8,10,"Trump's messaging style struggled as events exceeded earlier public framing.")},
{ "entry_number":1351,"title":"Trump's Iran Escalation Deepened Fears of Diplomatic Collapse After Leadership Shock","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's account suggested diplomacy would be harder after the reported killing because trust channels, interlocutors and deterrence assumptions all shifted at once. Trump entered a narrower negotiation space while facing broader deterrence burdens. The conflict became more brittle and harder to stabilize quickly.","rationale":"AP context indicated harder diplomacy and higher brittleness after leadership shock reporting.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["diplomatic collapse","trust channels","narrower space","deterrence burden","brittle conflict"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/c2f11247d8a66e36929266f2c557a54c","source_title":"Iran's supreme leader killed in major attack by US and Israel","source_publisher":"AP News","scores":make_scores("2026-02-28","Foreign Policy","Diplomatic Breakdown",9,7,9,6,3,3,8,10,"Trump's escalation trajectory made diplomatic stabilization more difficult.")},
{ "entry_number":1352,"title":"Trump's War Week Crossed From Pressure Politics Into Open Regional-System Destabilization","date_start":"2026-02-28","date_end":"2026-02-28","synopsis":"AP's reporting marked a transition point: what began as coercive leverage language now looked like system-level destabilization with uncertain endpoints. This shift matters because strategy calibrated for signaling often fails under regime-shock conditions. Trump's escalation entered a domain where consequences compound faster than narratives can adapt.","rationale":"AP coverage showed Trump's war timeline moving into broader systemic destabilization territory.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["system destabilization","pressure politics","uncertain endpoint","compounding consequences","strategic transition"],"metrics_key":"war","source_url":"https://apnews.com/article/c2f11247d8a66e36929266f2c557a54c","source_title":"Iran's supreme leader killed in major attack by US and Israel","source_publisher":"AP News","scores":make_scores("2026-02-28","Foreign Policy","Military Escalation",9,7,10,6,3,3,8,10,"Trump's escalation crossed into system-level destabilization with compounding risks.")},

{ "entry_number":1353,"title":"Trump Took the U.S. Into War Despite Years of 'America First' Non-Entanglement Branding","date_start":"2026-03-01","date_end":"2026-03-01","synopsis":"AP directly framed the contradiction: Trump entered war with Iran after decades of branding himself against Middle East entanglements. The political cost was not just hypocrisy rhetoric; it was credibility erosion across a coalition sold on restraint. Trump's identity message and policy execution diverged in full public view.","rationale":"AP highlighted contradiction between Trump's anti-entanglement brand and war action.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["America First","non-entanglement","brand contradiction","credibility erosion","war action"],"metrics_key":"governance","source_url":"https://apnews.com/article/23737d6fee8ae5aaf5a06627fd85a076","source_title":"Trump goes to war despite professed aversion to foreign entanglements, particularly in the Mideast","source_publisher":"AP News","scores":make_scores("2026-03-01","Conspiracy Theories / Disinformation","Systematic Presidential Lying",8,6,9,6,4,4,8,10,"Trump's anti-entanglement branding collided with his decision to enter war.")},
{ "entry_number":1354,"title":"Trump's Iran Decision Reversed a Core Promise to Prioritize the Western Hemisphere","date_start":"2026-03-01","date_end":"2026-03-01","synopsis":"AP noted Trump repeatedly said U.S. focus should stay closer to home, yet he committed to a major Middle East conflict cycle. That reversal mattered to voters who treated geographic-priority language as strategic doctrine, not campaign ornament. Trump's pivot widened distrust in his long-term policy commitments.","rationale":"AP reported a direct Trump reversal on geographic-priority foreign-policy promises.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["Western Hemisphere","promise reversal","Middle East war","policy trust","strategic doctrine"],"metrics_key":"governance","source_url":"https://apnews.com/article/23737d6fee8ae5aaf5a06627fd85a076","source_title":"Trump goes to war despite professed aversion to foreign entanglements, particularly in the Mideast","source_publisher":"AP News","scores":make_scores("2026-03-01","Conspiracy Theories / Disinformation","Systematic Presidential Lying",8,6,8,6,4,4,8,10,"Trump reversed stated geographic-priority doctrine by entering another Middle East war.")},
{ "entry_number":1355,"title":"Trump's Coalition Faced Internal Identity Shock as Anti-War Messaging Collapsed","date_start":"2026-03-01","date_end":"2026-03-01","synopsis":"AP's framing showed why intra-base conflict intensified: Trump's campaign identity was built on avoiding exactly this type of intervention. Once that line broke, movement coherence weakened and narrative discipline required heavier message management. The result was political fragmentation layered on top of military escalation.","rationale":"AP connected Trump's intervention choice to internal coalition identity fracture.","category":"Authoritarianism","subcategory":"Government Power Abuse","phase":"White House 2","keywords":["coalition shock","anti-war collapse","movement fracture","message management","identity conflict"],"metrics_key":"governance","source_url":"https://apnews.com/article/23737d6fee8ae5aaf5a06627fd85a076","source_title":"Trump goes to war despite professed aversion to foreign entanglements, particularly in the Mideast","source_publisher":"AP News","scores":make_scores("2026-03-01","Authoritarianism","Government Power Abuse",8,6,8,7,3,3,7,10,"Trump's war decision destabilized his own coalition's anti-war identity structure.")},
{ "entry_number":1356,"title":"Trump's Foreign-Policy Pivot Turned Campaign Rhetoric Into a Strategic Liability","date_start":"2026-03-01","date_end":"2026-03-01","synopsis":"According to AP, Trump's long-term rhetoric created expectations he later violated through intervention. In strategy terms, such reversals reduce credibility both domestically and abroad because commitments look contingent on political weather. Trump's own prior messaging became evidence against his current posture.","rationale":"AP showed Trump's previous rhetoric becoming a credibility liability once war began.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["strategic liability","rhetoric reversal","credibility loss","commitment risk","policy weather"],"metrics_key":"governance","source_url":"https://apnews.com/article/23737d6fee8ae5aaf5a06627fd85a076","source_title":"Trump goes to war despite professed aversion to foreign entanglements, particularly in the Mideast","source_publisher":"AP News","scores":make_scores("2026-03-01","Conspiracy Theories / Disinformation","Systematic Presidential Lying",8,6,8,6,4,4,8,10,"Trump's prior anti-war rhetoric became a credibility burden during intervention.")},
{ "entry_number":1357,"title":"Trump's Iran War Entry Strengthened the Case That His 'No New Wars' Claims Were Performative","date_start":"2026-03-01","date_end":"2026-03-01","synopsis":"AP's contradiction framing intensified a broader critique: Trump's restraint language functioned as political signaling more than governing constraint. Once combat expanded, opponents argued the slogan had always been conditional branding. The gap between declarative identity and operational behavior widened further.","rationale":"AP's own framing supported claims that Trump's restraint branding was conditional.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["no new wars","performative claim","conditional branding","combat expansion","identity gap"],"metrics_key":"governance","source_url":"https://apnews.com/article/23737d6fee8ae5aaf5a06627fd85a076","source_title":"Trump goes to war despite professed aversion to foreign entanglements, particularly in the Mideast","source_publisher":"AP News","scores":make_scores("2026-03-01","Conspiracy Theories / Disinformation","Systematic Presidential Lying",8,6,8,6,4,4,8,10,"Trump's intervention reinforced criticism that his anti-war brand was performative.")},
{ "entry_number":1358,"title":"Trump's War Choice Reopened War-Powers and Mandate Questions He Claimed to Settle Politically","date_start":"2026-03-01","date_end":"2026-03-01","synopsis":"Once Trump crossed into active conflict despite anti-entanglement branding, AP noted the resulting mandate confusion. If electoral messages promise one doctrine and execution follows another, congressional and public consent debates re-open fast. Trump's pivot invited exactly that democratic-legitimacy challenge.","rationale":"AP highlighted mandate confusion created by Trump's reversal into war.","category":"Election Interference","subcategory":"Democratic Institution Undermining","phase":"White House 2","keywords":["war powers","mandate confusion","electoral doctrine","consent debate","democratic legitimacy"],"metrics_key":"governance","source_url":"https://apnews.com/article/23737d6fee8ae5aaf5a06627fd85a076","source_title":"Trump goes to war despite professed aversion to foreign entanglements, particularly in the Mideast","source_publisher":"AP News","scores":make_scores("2026-03-01","Election Interference","Democratic Institution Undermining",8,7,8,7,3,3,7,10,"Trump's doctrinal reversal reignited mandate and war-powers legitimacy disputes.")},
{ "entry_number":1359,"title":"Trump's Mideast Intervention Undermined His Claim to Be the Predictable Anti-War Alternative","date_start":"2026-03-01","date_end":"2026-03-01","synopsis":"AP's framing captured a core reputational break: predictability was central to Trump's anti-war sales pitch, yet intervention made his doctrine appear conditional and volatile. For allies and adversaries, policy volatility increases misread risk. Trump's move therefore had messaging costs beyond domestic polling.","rationale":"AP showed Trump's intervention damaging his predictability claims.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["predictability claim","policy volatility","anti-war alternative","misread risk","reputational break"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/23737d6fee8ae5aaf5a06627fd85a076","source_title":"Trump goes to war despite professed aversion to foreign entanglements, particularly in the Mideast","source_publisher":"AP News","scores":make_scores("2026-03-01","Foreign Policy","Military Escalation",8,6,8,6,3,3,8,10,"Trump's war choice undercut claims that his foreign policy was predictably anti-war.")},

{ "entry_number":1360,"title":"Trump Said He Was 'Not Happy' With Iran Talks but Still Extended the Negotiation Clock","date_start":"2026-02-27","date_end":"2026-02-27","synopsis":"AP reported Trump publicly criticized the latest nuclear talks while also indicating negotiators would receive more time. The mixed line projected toughness and flexibility simultaneously, but it also increased ambiguity about U.S. red lines. Under pressure, Trump's strategy leaned on dual signaling rather than clear sequencing.","rationale":"AP showed Trump pairing talk criticism with timeline extension in one message cycle.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["not happy talks","more time","dual signaling","red lines","negotiation clock"],"metrics_key":"war","source_url":"https://apnews.com/article/436162f886bdaed30c8dd0cdbe1b5aea","source_title":"Trump says he is 'not happy' with the Iran nuclear talks but indicates he'll give them more time","source_publisher":"AP News","scores":make_scores("2026-02-27","Foreign Policy","Military Escalation",8,6,8,6,3,3,7,10,"Trump mixed hardline rhetoric with extended diplomacy timelines.")},
{ "entry_number":1361,"title":"Trump's Iran Messaging Combined Dissatisfaction Theater With Strategic Delay","date_start":"2026-02-27","date_end":"2026-02-27","synopsis":"AP described Trump using dissatisfaction language to preserve leverage while postponing final breakdown. This can be a negotiating tactic, but without transparent criteria it also looks like performative pressure politics. Trump's approach again favored headline posture over process clarity.","rationale":"AP reflected Trump's use of pressure rhetoric without clear public criteria.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["dissatisfaction theater","strategic delay","pressure rhetoric","process clarity","headline posture"],"metrics_key":"governance","source_url":"https://apnews.com/article/436162f886bdaed30c8dd0cdbe1b5aea","source_title":"Trump says he is 'not happy' with the Iran nuclear talks but indicates he'll give them more time","source_publisher":"AP News","scores":make_scores("2026-02-27","Conspiracy Theories / Disinformation","Systematic Presidential Lying",7,5,7,6,4,4,8,10,"Trump used hardline posture language while keeping criteria for escalation opaque.")},
{ "entry_number":1362,"title":"Trump's 'More Time' Line Delayed Resolution but Did Not Reduce Escalation Anxiety","date_start":"2026-02-27","date_end":"2026-02-27","synopsis":"AP's framing showed that extending talks did not automatically reassure observers because military and political tension remained high. Under Trump's model, time extension worked as tactical breathing room rather than a clear de-escalation commitment. The uncertainty premium stayed in place.","rationale":"AP showed timeline extension without corresponding drop in escalation concern.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["more time","escalation anxiety","tactical breathing room","uncertainty premium","de-escalation gap"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/436162f886bdaed30c8dd0cdbe1b5aea","source_title":"Trump says he is 'not happy' with the Iran nuclear talks but indicates he'll give them more time","source_publisher":"AP News","scores":make_scores("2026-02-27","Foreign Policy","Diplomatic Breakdown",8,6,8,6,3,3,7,10,"Trump's timeline extension failed to eliminate broad escalation fears.")},
{ "entry_number":1363,"title":"Trump's Iran Talk Stance Became a Pre-War Contradiction Once Combat Expanded Days Later","date_start":"2026-02-27","date_end":"2026-03-01","synopsis":"AP's Feb. 27 reporting on giving talks more time became politically explosive once war intensified shortly afterward. The chronology sharpened criticism that Trump's diplomacy language was transitional messaging rather than durable strategy. Timeline compression made contradictions easier for the public to see.","rationale":"AP timeline made Trump's diplomacy-to-war shift appear abrupt and contradictory.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["pre-war contradiction","timeline compression","diplomacy shift","durable strategy","public chronology"],"metrics_key":"war","source_url":"https://apnews.com/article/436162f886bdaed30c8dd0cdbe1b5aea","source_title":"Trump says he is 'not happy' with the Iran nuclear talks but indicates he'll give them more time","source_publisher":"AP News","scores":make_scores("2026-02-27","Conspiracy Theories / Disinformation","Systematic Presidential Lying",8,6,8,6,4,4,8,10,"Trump's talk-extension message quickly collided with rapid escalation days later.")},
{ "entry_number":1364,"title":"Trump's Negotiation Language Preserved Tactical Optionality While Weakening Strategic Trust","date_start":"2026-02-27","date_end":"2026-02-27","synopsis":"AP's account reflected the tradeoff in Trump's style: flexible rhetoric can preserve options, but repeated ambiguity degrades trust among allies, opponents and domestic audiences. When everyone hears multiple futures at once, commitment signals weaken. Trump's approach again optimized short-term maneuver over long-term predictability.","rationale":"AP highlighted ambiguity costs in Trump's option-preserving negotiation language.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["tactical optionality","strategic trust","ambiguity cost","commitment signal","predictability"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/436162f886bdaed30c8dd0cdbe1b5aea","source_title":"Trump says he is 'not happy' with the Iran nuclear talks but indicates he'll give them more time","source_publisher":"AP News","scores":make_scores("2026-02-27","Foreign Policy","Diplomatic Breakdown",8,6,8,6,3,3,7,10,"Trump's flexible messaging protected options but reduced strategic trust.")},
{ "entry_number":1365,"title":"Trump's Iran Talk Position Demonstrated How He Converts Policy into Perpetual Leverage Theater","date_start":"2026-02-27","date_end":"2026-02-27","synopsis":"AP showed a familiar pattern: announce dissatisfaction, preserve space, and keep pressure language active. The method keeps Trump's personal leverage central but can leave institutions and partners unclear on decision thresholds. In crisis environments, that ambiguity itself becomes a risk multiplier.","rationale":"AP reflected Trump's recurring leverage-theater approach to high-risk diplomacy.","category":"Authoritarianism","subcategory":"Government Power Abuse","phase":"White House 2","keywords":["leverage theater","decision thresholds","pressure language","institutional ambiguity","risk multiplier"],"metrics_key":"governance","source_url":"https://apnews.com/article/436162f886bdaed30c8dd0cdbe1b5aea","source_title":"Trump says he is 'not happy' with the Iran nuclear talks but indicates he'll give them more time","source_publisher":"AP News","scores":make_scores("2026-02-27","Authoritarianism","Government Power Abuse",7,6,7,7,3,3,7,10,"Trump centered personal leverage signaling over clear institutional decision thresholds.")},
{ "entry_number":1366,"title":"Trump's Iran Timeline Messaging Left Congress and Allies Interpreting Intent in Real Time","date_start":"2026-02-27","date_end":"2026-02-27","synopsis":"Because AP reported both dissatisfaction and extension in the same cycle, outside stakeholders had to infer intent from tone rather than explicit doctrine. This interpretation burden weakens coordinated policy execution. Trump's compressed mixed messaging made governance harder exactly when clarity mattered most.","rationale":"AP showed stakeholders forced to infer intent from Trump's mixed timing signals.","category":"Election Interference","subcategory":"Democratic Institution Undermining","phase":"White House 2","keywords":["intent inference","mixed signals","congressional interpretation","ally interpretation","doctrine gap"],"metrics_key":"governance","source_url":"https://apnews.com/article/436162f886bdaed30c8dd0cdbe1b5aea","source_title":"Trump says he is 'not happy' with the Iran nuclear talks but indicates he'll give them more time","source_publisher":"AP News","scores":make_scores("2026-02-27","Election Interference","Democratic Institution Undermining",7,7,7,7,3,3,7,10,"Trump's mixed timeline signaling forced Congress and allies to infer policy intent.")},

{ "entry_number":1367,"title":"Trump Was Branded a 'Criminal' by Iran's Supreme Leader After Publicly Backing Protests","date_start":"2026-01-17","date_end":"2026-01-17","synopsis":"AP reported Khamenei publicly called Trump a criminal for support of demonstrators and blamed protesters for deaths. The statement intensified the personal nature of U.S.-Iran confrontation and raised rhetorical temperature ahead of later military escalation. Under Trump, political messaging and geopolitical escalation were tightly coupled.","rationale":"AP documented direct personal denunciation of Trump by Iran's top leadership.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["criminal label","Khamenei statement","protest support","rhetorical escalation","US-Iran tension"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/fc11b1082fb75fca02205f668c822751","source_title":"Iran's leader calls Trump a 'criminal' for backing protests and blames demonstrators for deaths","source_publisher":"AP News","scores":make_scores("2026-01-17","Foreign Policy","Diplomatic Breakdown",7,6,7,6,3,3,7,9,"Iranian leadership issued direct personal denunciations of Trump amid protest tensions.")},
{ "entry_number":1368,"title":"Trump's Protest-Backing Rhetoric Triggered Counter-Narratives That Framed U.S. Policy as Destabilization","date_start":"2026-01-17","date_end":"2026-01-17","synopsis":"AP's report showed Iranian leadership reframing Trump's protest language as hostile interference. This narrative battle mattered because it shaped domestic legitimacy contests inside Iran and external diplomacy at the same time. Trump's hardline signaling increased backlash framing opportunities for adversaries.","rationale":"AP showed Trump's protest posture fueling interference narratives from Tehran.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["interference narrative","protest rhetoric","backlash framing","legitimacy contest","Tehran response"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/fc11b1082fb75fca02205f668c822751","source_title":"Iran's leader calls Trump a 'criminal' for backing protests and blames demonstrators for deaths","source_publisher":"AP News","scores":make_scores("2026-01-17","Foreign Policy","Diplomatic Breakdown",7,6,7,6,3,3,7,9,"Trump's protest messaging enabled adversarial interference counter-framing.")},
{ "entry_number":1369,"title":"Trump's Early-2026 Iran Rhetoric Set a Confrontational Baseline Later Overtaken by War","date_start":"2026-01-17","date_end":"2026-01-17","synopsis":"AP's January reporting showed direct rhetorical confrontation long before open war acceleration. Seen in hindsight, those exchanges established a baseline of hardened positions and personal antagonism. Trump's language strategy reduced diplomatic elasticity before the most dangerous phase arrived.","rationale":"AP January coverage showed confrontational rhetoric that prefigured later escalation.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["confrontational baseline","early warning","hardened positions","diplomatic elasticity","pre-war rhetoric"],"metrics_key":"diplomacy","source_url":"https://apnews.com/article/fc11b1082fb75fca02205f668c822751","source_title":"Iran's leader calls Trump a 'criminal' for backing protests and blames demonstrators for deaths","source_publisher":"AP News","scores":make_scores("2026-01-17","Foreign Policy","Military Escalation",8,6,8,6,3,3,7,9,"Trump's early rhetoric reduced flexibility before later war escalation.")},

{ "entry_number":1370,"title":"Rolling Stone Analysis Argued Trump's Iran War Narrative Lacked a Coherent Endgame","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"A March 3 Rolling Stone commentary argued Trump's Iran-war case was built on unstable assumptions and lacked a clear objective path. While opinion journalism is interpretive, the critique tracked broader reporting concerns about goal clarity and legal process. The piece amplified a growing consensus that Trump was escalating faster than his strategy could explain.","rationale":"Rolling Stone's analysis reinforced concerns about absent Trump endgame clarity in Iran.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["endgame clarity","opinion analysis","war narrative","strategic assumptions","goal ambiguity"],"metrics_key":"governance","source_url":"https://www.rollingstone.com/politics/political-commentary/trump-war-iran-lies-fantasies-1235524016/","source_title":"Trump's Iran War Is Built on Lies and Fantasies","source_publisher":"Rolling Stone","scores":make_scores("2026-03-03","Conspiracy Theories / Disinformation","Systematic Presidential Lying",8,6,8,6,4,4,8,10,"External analysis echoed concerns that Trump's war narrative lacked coherent objectives.")},
]

entry_cols=["entry_number","title","date_start","date_end","synopsis","rationale","category","subcategory","keywords","age","phase","impressions","reach_estimate","financial_cost_usd","public_reaction","fact_check","fact_check_sources","scores"]
score_cols=["entry_number","insanity","absurdity","danger","authoritarianism","lawlessness","credibility_risk","recency_intensity","impact_scope","rationale_short","rationale_detail"]
source_cols=["entry_number","url","title","publisher","date_published","source_type"]

entry_vals=[]; score_vals=[]; source_vals=[]; keyword_vals=[]
for e in entries:
    m=metrics[e["metrics_key"]]
    e["impressions"]=m["impressions"]; e["reach_estimate"]=m["reach_estimate"]; e["financial_cost_usd"]=m["financial_cost_usd"]; e["public_reaction"]=m["public_reaction"]; e["age"]=calc_age(e["date_start"])
    s=e["scores"]
    entry_vals.append("("+", ".join([
        str(e["entry_number"]),f"'{sql_escape(e['title'])}'",f"'{e['date_start']}'",f"'{e['date_end']}'",f"'{sql_escape(e['synopsis'])}'",f"'{sql_escape(e['rationale'])}'",f"'{sql_escape(e['category'])}'",f"'{sql_escape(e['subcategory'])}'",arr_sql(e["keywords"]),str(e["age"]),f"'{sql_escape(e['phase'])}'",str(e["impressions"]),str(e["reach_estimate"]),str(e["financial_cost_usd"]),json_sql(e["public_reaction"]),"NULL","ARRAY[]::text[]",json_sql(s)
    ])+")")
    score_vals.append("("+", ".join([
        str(e["entry_number"]),str(s["insanity"]),str(s["absurdity"]),str(s["danger"]),str(s["authoritarianism"]),str(s["lawlessness"]),str(s["credibility_risk"]),str(s["recency_intensity"]),str(s["impact_scope"]),f"'{sql_escape(s['rationale_short'])}'",f"'{sql_escape(s['rationale_detail'])}'"
    ])+")")
    source_vals.append("("+", ".join([
        str(e["entry_number"]),f"'{sql_escape(e['source_url'])}'",f"'{sql_escape(e['source_title'])}'",f"'{sql_escape(e['source_publisher'])}'",f"'{e['date_start']}'",f"'news'"
    ])+")")
    for kw in e["keywords"]: keyword_vals.append("("+", ".join([str(e["entry_number"]),f"'{sql_escape(kw)}'"])+")")

sql_entries="INSERT INTO public.trump_entries ("+", ".join(entry_cols)+") VALUES\n"+",\n".join(entry_vals)+"\nON CONFLICT DO NOTHING;"
sql_scores="INSERT INTO public.trump_individual_scores ("+", ".join(score_cols)+") VALUES\n"+",\n".join(score_vals)+"\nON CONFLICT DO NOTHING;"
sql_sources="INSERT INTO public.trump_sources ("+", ".join(source_cols)+") VALUES\n"+",\n".join(source_vals)+";"
sql_keywords="INSERT INTO public.trump_keywords (entry_number, keyword) VALUES\n"+",\n".join(keyword_vals)+"\nON CONFLICT DO NOTHING;"
print(json.dumps([sql_entries,sql_scores,sql_sources,sql_keywords],indent=2))
