import json
from datetime import datetime

months=["Jan.","Feb.","Mar.","Apr.","May","Jun.","Jul.","Aug.","Sep.","Oct.","Nov.","Dec."]
birth_date=datetime(1946,6,14)

def format_date(date_str:str)->str:
    d=datetime.strptime(date_str,"%Y-%m-%d")
    return f"{months[d.month-1]} {d.day}, {d.year}"

def calc_age(date_str:str)->int:
    d=datetime.strptime(date_str,"%Y-%m-%d")
    a=d.year-birth_date.year
    if (d.month,d.day)<(birth_date.month,birth_date.day): a-=1
    return a

def sql_escape(v:str)->str: return v.replace("'","''")
def json_sql(o)->str: return "'"+json.dumps(o,separators=(",",":"),ensure_ascii=True).replace("'","''")+"'::jsonb"
def arr_sql(items)->str:
    if not items: return "ARRAY[]::text[]"
    return "ARRAY["+",".join("'"+sql_escape(x)+"'" for x in items)+"]::text[]"

def make_scores(date_start,category,subcategory,danger,lawlessness,impact_scope,authoritarianism,insanity,absurdity,credibility_risk,recency_intensity,rationale_short):
    return {
        "danger":danger,"insanity":insanity,"absurdity":absurdity,"lawlessness":lawlessness,"impact_scope":impact_scope,
        "rationale_short":rationale_short,"authoritarianism":authoritarianism,"credibility_risk":credibility_risk,
        "rationale_detail":f"{category}: {subcategory}. On {format_date(date_start)}, {rationale_short}","recency_intensity":recency_intensity,
    }

metrics={
    "war":{"impressions":191000000,"reach_estimate":668000000,"financial_cost_usd":980000000,"public_reaction":{"negative":79,"neutral":15,"positive":6}},
    "diplomacy":{"impressions":163000000,"reach_estimate":552000000,"financial_cost_usd":430000000,"public_reaction":{"negative":75,"neutral":18,"positive":7}},
    "governance":{"impressions":151000000,"reach_estimate":520000000,"financial_cost_usd":260000000,"public_reaction":{"negative":77,"neutral":16,"positive":7}},
}

entries=[
{ "entry_number":1296,"title":"Trump Launched a TV Surrogate Blitz to Defend Iran Strikes and Shrink Epstein Questions","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP reported that the White House rolled out loyal officials across television to defend Trump’s Iran operation while criticism spread that the war timing was politically convenient. Instead of letting independent investigators or Congress set the frame, Trump’s team tried to drown out domestic scandal narratives with message discipline and wartime posture. The communications strategy itself became part of the story.","rationale":"AP documented a coordinated Trump media defense operation tied to Iran-strike fallout.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["media blitz","Iran strikes","Epstein questions","surrogates","message control"],"metrics_key":"governance","source_url":"https://apnews.com/article/iran-trump-administration-media-communication-2aeb11fcfef4138c045be71fb7216792","source_title":"White House sends top officials to defend Trump’s Iran policy amid scrutiny","source_publisher":"AP News","scores":make_scores("2026-03-03","Conspiracy Theories / Disinformation","Systematic Presidential Lying",7,5,8,6,3,4,8,10,"Trump deployed a coordinated media shield as Iran-war criticism and Epstein scrutiny converged.")},
{ "entry_number":1297,"title":"Trump Framed Iran Escalation as National Security While Critics Called It Political Cover","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"In AP’s account, Trump’s allies insisted the Iran strikes were purely strategic, while public critics argued the timing looked like distraction from growing Epstein-file controversy. The clash was less about one quote and more about credibility: when a president facing scandal escalates conflict, every operational claim is viewed through a domestic political lens. Trump’s trust deficit amplified that suspicion.","rationale":"AP captured competing narratives around Trump’s motives for escalation during scandal pressure.","category":"Government Corruption","subcategory":"Transparency Obstruction","phase":"White House 2","keywords":["political cover","war narrative","credibility gap","scandal pressure","Trump motives"],"metrics_key":"governance","source_url":"https://apnews.com/article/iran-trump-administration-media-communication-2aeb11fcfef4138c045be71fb7216792","source_title":"White House sends top officials to defend Trump’s Iran policy amid scrutiny","source_publisher":"AP News","scores":make_scores("2026-03-03","Government Corruption","Transparency Obstruction",7,6,8,6,3,4,8,10,"Trump’s Iran justification met immediate credibility challenges tied to concurrent scandal pressure.")},
{ "entry_number":1298,"title":"Trump War Messaging Echoed His Legal-Crisis Playbook: Deny, Flood, Redirect","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP noted that Trump’s media handling of Iran criticism resembled patterns seen during his court fights: attack the premise, flood channels with loyal messengers, and move the conversation to a narrative where he controls definitions. That continuity mattered because it blurred the line between wartime public communication and personal political damage control. The method looked familiar even if the stakes were global.","rationale":"AP described a Trump communications pattern that mirrored prior legal-defense tactics.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["deny flood redirect","legal playbook","war communication","damage control","Trump pattern"],"metrics_key":"governance","source_url":"https://apnews.com/article/iran-trump-administration-media-communication-2aeb11fcfef4138c045be71fb7216792","source_title":"White House sends top officials to defend Trump’s Iran policy amid scrutiny","source_publisher":"AP News","scores":make_scores("2026-03-03","Conspiracy Theories / Disinformation","Systematic Presidential Lying",7,5,8,6,4,4,8,10,"Trump’s Iran messaging mirrored his legal-crisis media playbook.")},
{ "entry_number":1299,"title":"Trump Relied on Personality Politics Over Institutional Briefing to Sell Iran Action","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"Rather than centering congressional testimony and bipartisan briefings, AP described a strategy anchored in personalities, television hits, and loyalty messaging. Trump again prioritized media theater as a governing instrument, especially on foreign policy where verification lags behind claims. That approach raised the risk that narrative management could outrun transparent accountability in real time.","rationale":"AP showed Trump favoring media personalities over formal transparency channels.","category":"Authoritarianism","subcategory":"Government Power Abuse","phase":"White House 2","keywords":["institutional bypass","tv strategy","accountability","personality politics","briefing gap"],"metrics_key":"governance","source_url":"https://apnews.com/article/iran-trump-administration-media-communication-2aeb11fcfef4138c045be71fb7216792","source_title":"White House sends top officials to defend Trump’s Iran policy amid scrutiny","source_publisher":"AP News","scores":make_scores("2026-03-03","Authoritarianism","Government Power Abuse",7,6,7,7,3,3,7,10,"Trump prioritized media loyalty circuits over institutional transparency during war messaging.")},
{ "entry_number":1300,"title":"Trump’s Iran Media Push Turned Foreign Policy Into a Domestic Narrative Battlefield","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP’s reporting showed Trump folding an active conflict into domestic identity combat, where support for strikes became a proxy test of personal loyalty. That framing compresses complex policy into tribal signaling and makes correction harder once facts change. The result was a foreign-policy discussion increasingly run as campaign rhetoric under wartime conditions.","rationale":"AP showed Trump politicizing wartime communication into loyalty-based domestic messaging.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["domestic battlefield","loyalty test","identity politics","wartime rhetoric","information war"],"metrics_key":"governance","source_url":"https://apnews.com/article/iran-trump-administration-media-communication-2aeb11fcfef4138c045be71fb7216792","source_title":"White House sends top officials to defend Trump’s Iran policy amid scrutiny","source_publisher":"AP News","scores":make_scores("2026-03-03","Conspiracy Theories / Disinformation","Systematic Presidential Lying",7,5,8,6,4,4,8,10,"Trump reframed war communication as a domestic loyalty fight.")},

{ "entry_number":1301,"title":"Trump Said He Was Open to Talks While Military Operations Continued to Expand","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP and PBS coverage both captured Trump signaling eventual talks with Iran while combat operations remained active. The contradiction was strategic and rhetorical: diplomacy language was offered publicly, but coercive pressure kept intensifying in practice. That dual track created confusion about whether Washington sought de-escalation terms or escalation leverage first.","rationale":"AP/PBS showed Trump pairing talk signals with ongoing military expansion.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["open to talks","ongoing strikes","mixed signals","dual track","de-escalation doubt"],"metrics_key":"war","source_url":"https://www.pbs.org/newshour/world/white-house-official-irans-new-potential-leadership-suggests-its-open-to-talks-and-trump-says-hes-eventually-willing","source_title":"White House official says potential Iranian leadership could be open to talks","source_publisher":"PBS NewsHour","scores":make_scores("2026-03-03","Foreign Policy","Military Escalation",8,6,9,6,3,3,7,10,"Trump’s public openness to talks ran alongside expanding military pressure.")},
{ "entry_number":1302,"title":"Trump Kept Publicly Framing Iran Operation as Limited While Regional Risk Kept Growing","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"In AP’s regional-war update, the operational footprint kept broadening across diplomacy, security alerts and retaliatory threats even as Trump messaging stressed control and bounded objectives. The mismatch between language and conditions mattered because allies and markets price risk from actual escalation pathways, not from comforting soundbites. Trump’s framing repeatedly lagged events.","rationale":"AP showed widening conflict conditions despite Trump’s bounded-war framing.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["limited war claim","regional spread","risk pricing","retaliation fears","operational mismatch"],"metrics_key":"war","source_url":"https://apnews.com/article/iran-israel-us-03-03-2026-8755877b603e46ed3df8107689c1ee23","source_title":"Live updates: Iran conflict widens as U.S. and Israel continue operations","source_publisher":"AP News","scores":make_scores("2026-03-03","Foreign Policy","Military Escalation",8,6,9,6,3,3,8,10,"Trump described control while regional escalation indicators kept increasing.")},
{ "entry_number":1303,"title":"Trump’s Iran Strategy Left Allies Managing Fallout Faster Than Washington Could Clarify Goals","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP’s live conflict reporting highlighted how allied governments moved quickly on protection, warnings and emergency posture while U.S. political messaging remained contested at home. Under Trump, objective-setting and consequence management appeared out of sync, forcing partners to improvise around uncertainty. That asymmetry increased diplomatic strain in real time.","rationale":"AP showed allied fallout management outpacing Trump goal clarity.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["allied fallout","goal clarity","diplomatic strain","emergency posture","uncertainty"],"metrics_key":"war","source_url":"https://apnews.com/article/iran-israel-us-03-03-2026-8755877b603e46ed3df8107689c1ee23","source_title":"Live updates: Iran conflict widens as U.S. and Israel continue operations","source_publisher":"AP News","scores":make_scores("2026-03-03","Foreign Policy","Military Escalation",8,6,9,6,3,3,8,10,"Trump’s objective messaging lagged allied crisis-management needs.")},
{ "entry_number":1304,"title":"Trump’s Escalation Week Intensified Global Alert Cycles Around Energy and Shipping Risk","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP’s updates tied ongoing operations to broader regional-risk concerns that traditionally spill into shipping insurance, energy volatility and civilian safety planning. Even when immediate battlefield details changed hour by hour, the macro effect was persistent uncertainty. Trump’s posture kept markets and allied planners on emergency footing rather than confidence footing.","rationale":"AP linked continued operations under Trump to wider regional-risk amplification.","category":"Foreign Policy","subcategory":"Economic Warfare","phase":"White House 2","keywords":["shipping risk","energy volatility","regional alert","market uncertainty","emergency footing"],"metrics_key":"war","source_url":"https://apnews.com/article/iran-israel-us-03-03-2026-8755877b603e46ed3df8107689c1ee23","source_title":"Live updates: Iran conflict widens as U.S. and Israel continue operations","source_publisher":"AP News","scores":make_scores("2026-03-03","Foreign Policy","Economic Warfare",8,6,9,6,3,3,7,10,"Trump-era escalation sustained energy and logistics risk signals across the region.")},
{ "entry_number":1305,"title":"Trump’s Conflict Management Prioritized Optics Even as Operational Complexity Increased","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"Across AP’s war coverage and communication reporting, Trump’s team repeatedly returned to optics-first framing while military and diplomatic conditions became more complex. That imbalance is dangerous because narrative simplification can hide second-order risks until they mature into crises. The gap between performance and planning became increasingly visible.","rationale":"AP reporting showed optics-heavy messaging amid rising operational complexity under Trump.","category":"Authoritarianism","subcategory":"Government Power Abuse","phase":"White House 2","keywords":["optics first","complexity gap","second-order risk","performance politics","crisis management"],"metrics_key":"war","source_url":"https://apnews.com/article/iran-trump-administration-media-communication-2aeb11fcfef4138c045be71fb7216792","source_title":"White House sends top officials to defend Trump’s Iran policy amid scrutiny","source_publisher":"AP News","scores":make_scores("2026-03-03","Authoritarianism","Government Power Abuse",8,6,8,7,3,3,7,10,"Trump leaned on optics while conflict-management complexity kept rising.")},

{ "entry_number":1306,"title":"Trump Drew Bipartisan Backlash After Reports He Did Not Brief Key Congressional Leaders","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP reported criticism from both parties over the handling of congressional consultation before strikes. Under constitutional design, major military actions require more than rhetorical justification; they require accountable process. Trump’s approach reignited the long-running war-powers conflict between executive momentum and legislative oversight.","rationale":"AP described bipartisan criticism of Trump’s congressional-briefing process on Iran strikes.","category":"Election Interference","subcategory":"Democratic Institution Undermining","phase":"White House 2","keywords":["war powers","congressional briefing","bipartisan backlash","oversight","constitutional process"],"metrics_key":"governance","source_url":"https://apnews.com/article/trump-iran-maga-regime-change-2758513ac034ffb75beaa12db68c7bd7","source_title":"Trump faces criticism from left and right over Iran strike planning","source_publisher":"AP News","scores":make_scores("2026-03-03","Election Interference","Democratic Institution Undermining",8,7,8,7,3,3,7,10,"Trump’s reported pre-strike process triggered bipartisan war-powers criticism.")},
{ "entry_number":1307,"title":"Trump’s Iran Decision Split His Own Base as America-First Factions Broke Ranks","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP coverage showed the internal fracture clearly: pro-intervention conservatives defended force while prominent America-First voices argued Trump had abandoned core anti-war promises. The split was politically significant because it pierced the idea of automatic movement discipline. Trump’s foreign-policy pivot exposed coalition fault lines he usually controls.","rationale":"AP documented a real MAGA coalition split over Trump’s Iran escalation.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["base split","America First","anti-war pledge","coalition fracture","MAGA backlash"],"metrics_key":"governance","source_url":"https://apnews.com/article/trump-iran-maga-regime-change-2758513ac034ffb75beaa12db68c7bd7","source_title":"Trump faces criticism from left and right over Iran strike planning","source_publisher":"AP News","scores":make_scores("2026-03-03","Conspiracy Theories / Disinformation","Systematic Presidential Lying",7,5,8,6,3,4,8,10,"Trump’s Iran turn fractured his own anti-war political coalition.")},
{ "entry_number":1308,"title":"Trump’s Team Defended Strikes as Necessary While Critics Demanded a Legal Basis in Public","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP described a widening argument over legal authority and necessity claims, with Trump allies emphasizing urgency while opponents sought explicit statutory and constitutional grounding. This conflict is not academic: legal ambiguity in war decisions reduces democratic consent and increases policy volatility. Trump’s handling left the legitimacy argument unresolved.","rationale":"AP highlighted unresolved legal-authority disputes in Trump’s strike defense.","category":"Authoritarianism","subcategory":"Government Power Abuse","phase":"White House 2","keywords":["legal basis","necessity claim","authority dispute","democratic consent","legitimacy"],"metrics_key":"governance","source_url":"https://apnews.com/article/trump-iran-maga-regime-change-2758513ac034ffb75beaa12db68c7bd7","source_title":"Trump faces criticism from left and right over Iran strike planning","source_publisher":"AP News","scores":make_scores("2026-03-03","Authoritarianism","Government Power Abuse",8,7,8,7,3,3,7,10,"Trump’s strike justification left major legal-authority questions publicly unresolved.")},
{ "entry_number":1309,"title":"Trump’s Iran Pivot Reopened Questions About Whether Campaign Non-Intervention Promises Were Real","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"As AP noted, critics from inside and outside Trump’s coalition argued the operation contradicted his anti-war political branding. The issue was less about one tactical decision and more about truth-in-governance: whether campaign identity statements were durable commitments or flexible slogans. The discrepancy fed broader credibility erosion.","rationale":"AP coverage amplified contradiction between Trump’s anti-war branding and wartime action.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["anti-war branding","promise reversal","credibility erosion","campaign identity","foreign policy pivot"],"metrics_key":"governance","source_url":"https://apnews.com/article/trump-iran-maga-regime-change-2758513ac034ffb75beaa12db68c7bd7","source_title":"Trump faces criticism from left and right over Iran strike planning","source_publisher":"AP News","scores":make_scores("2026-03-03","Conspiracy Theories / Disinformation","Systematic Presidential Lying",7,5,8,6,3,4,8,10,"Trump’s anti-war campaign identity collided with his wartime escalation decisions.")},
{ "entry_number":1310,"title":"Trump’s War-Room Politics Drew Charges of Process Failure Before Policy Failure","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP’s report showed criticism centered not only on outcomes but on sequencing: consultation, legal explanation, and objective communication were all contested before battlefield results were even clear. That is a governance red flag because process legitimacy is what holds strategic choices together under uncertainty. Trump’s approach strained that foundation.","rationale":"AP criticism focused on Trump’s decision process as much as battlefield outcomes.","category":"Authoritarianism","subcategory":"Government Power Abuse","phase":"White House 2","keywords":["process failure","war room politics","consultation gap","objective clarity","governance stress"],"metrics_key":"governance","source_url":"https://apnews.com/article/trump-iran-maga-regime-change-2758513ac034ffb75beaa12db68c7bd7","source_title":"Trump faces criticism from left and right over Iran strike planning","source_publisher":"AP News","scores":make_scores("2026-03-03","Authoritarianism","Government Power Abuse",8,7,8,7,3,3,7,10,"Trump faced process-legitimacy criticism before military outcomes were settled.")},

{ "entry_number":1311,"title":"Trump Pressed UK Alignment but Starmer Publicly Refused to Back Iran Strikes","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"The Guardian reported that UK Prime Minister Keir Starmer rejected requests to endorse Trump’s strikes, creating a visible split between Washington and a key ally. Public refusal at this level signaled more than tactical disagreement; it signaled mistrust in strategy and legal framing. Trump’s coalition management abroad weakened at a high-visibility moment.","rationale":"Guardian reported direct UK refusal to support Trump’s Iran strikes.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["UK refusal","Starmer","allied split","diplomatic strain","Iran strikes"],"metrics_key":"diplomacy","source_url":"https://www.theguardian.com/us-news/2026/mar/03/trump-starmer-uk-refusal-back-iran-strikes","source_title":"Starmer refuses to back Trump on Iran strikes","source_publisher":"The Guardian","scores":make_scores("2026-03-03","Foreign Policy","Diplomatic Breakdown",8,6,8,6,3,3,7,10,"Trump failed to secure UK support, exposing allied mistrust over Iran strategy.")},
{ "entry_number":1312,"title":"Trump’s Iran Escalation Produced a Public US-UK Foreign-Policy Rift","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"According to The Guardian, Starmer’s refusal transformed private alliance friction into public divergence, undercutting Trump’s claim of broad democratic backing for escalation. Diplomatic unity often serves as strategic deterrence; visible fractures do the opposite. Trump’s move therefore carried both military and alliance costs.","rationale":"Guardian showed Trump’s approach causing an overt public alliance split.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["US-UK rift","public divergence","alliance cost","deterrence","Trump diplomacy"],"metrics_key":"diplomacy","source_url":"https://www.theguardian.com/us-news/2026/mar/03/trump-starmer-uk-refusal-back-iran-strikes","source_title":"Starmer refuses to back Trump on Iran strikes","source_publisher":"The Guardian","scores":make_scores("2026-03-03","Foreign Policy","Diplomatic Breakdown",8,6,8,6,3,3,7,10,"Trump’s Iran stance turned allied friction into a visible US-UK split.")},
{ "entry_number":1313,"title":"Trump’s Pressure Politics With Allies Backfired During the Iran Crisis Window","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"Guardian reporting suggested Trump sought alignment through pressure but received resistance instead. In crisis diplomacy, coercing allies can reduce trust just when coordinated de-escalation channels are most needed. The refusal from London highlighted limits of Trump’s transactional style under high-risk conditions.","rationale":"Guardian showed Trump’s pressure approach failing to produce allied compliance.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["pressure politics","ally resistance","transactional diplomacy","crisis window","de-escalation channels"],"metrics_key":"diplomacy","source_url":"https://www.theguardian.com/us-news/2026/mar/03/trump-starmer-uk-refusal-back-iran-strikes","source_title":"Starmer refuses to back Trump on Iran strikes","source_publisher":"The Guardian","scores":make_scores("2026-03-03","Foreign Policy","Diplomatic Breakdown",8,6,8,6,3,3,7,10,"Trump’s pressure-based alliance management failed in a high-risk Iran moment.")},
{ "entry_number":1314,"title":"Trump’s Coalition Narrative Took a Hit as Britain Declined Strike Endorsement","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"The Guardian’s account of UK refusal weakened Trump’s attempts to present the Iran operation as broadly aligned among close partners. Narrative matters in war because coalition legitimacy affects domestic support, adversary calculus and negotiation leverage. Trump’s version of consensus was publicly punctured.","rationale":"Guardian reporting undercut Trump’s claim of broad allied alignment.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["coalition narrative","allied endorsement","legitimacy","consensus claim","strategic messaging"],"metrics_key":"diplomacy","source_url":"https://www.theguardian.com/us-news/2026/mar/03/trump-starmer-uk-refusal-back-iran-strikes","source_title":"Starmer refuses to back Trump on Iran strikes","source_publisher":"The Guardian","scores":make_scores("2026-03-03","Conspiracy Theories / Disinformation","Systematic Presidential Lying",7,5,8,6,3,4,8,10,"Trump’s coalition-credibility claims were damaged by Britain’s explicit refusal.")},
{ "entry_number":1315,"title":"Trump’s Iran Escalation Left Even Friendly Governments Prioritizing Distance Over Endorsement","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"Guardian coverage reflected a pattern: allies sought space from Trump’s strike posture instead of public co-ownership. That distancing behavior is a diplomatic signal that partners assess political and legal downside as too high. Trump’s escalation therefore narrowed his room to claim multilateral legitimacy.","rationale":"Guardian showed allies distancing themselves from Trump’s strike posture.","category":"Foreign Policy","subcategory":"Diplomatic Breakdown","phase":"White House 2","keywords":["ally distancing","endorsement refusal","multilateral legitimacy","political downside","Iran posture"],"metrics_key":"diplomacy","source_url":"https://www.theguardian.com/us-news/2026/mar/03/trump-starmer-uk-refusal-back-iran-strikes","source_title":"Starmer refuses to back Trump on Iran strikes","source_publisher":"The Guardian","scores":make_scores("2026-03-03","Foreign Policy","Diplomatic Breakdown",8,6,8,6,3,3,7,10,"Trump’s escalation pushed allies toward public distance rather than support.")},

{ "entry_number":1316,"title":"Trump Claimed Openness to Negotiation While Signaling Continued Coercive Leverage","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"PBS reported White House signals that potential leadership channels in Iran could allow talks, while Trump simultaneously maintained coercive leverage framing. The contradiction can be intentional, but under Trump it also read as message volatility, because tactical statements shifted quickly and often lacked procedural follow-through. Diplomatic signals became harder to parse.","rationale":"PBS showed Trump blending negotiation language with continued coercive signaling.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["open to negotiation","coercive leverage","message volatility","talk channels","Trump signaling"],"metrics_key":"war","source_url":"https://www.pbs.org/newshour/world/white-house-official-irans-new-potential-leadership-suggests-its-open-to-talks-and-trump-says-hes-eventually-willing","source_title":"White House official says potential Iranian leadership could be open to talks","source_publisher":"PBS NewsHour","scores":make_scores("2026-03-03","Foreign Policy","Military Escalation",8,6,8,6,3,3,7,10,"Trump mixed negotiation rhetoric with sustained coercive positioning.")},
{ "entry_number":1317,"title":"Trump’s ‘Eventually Willing’ Talk Formula Prolonged Uncertainty About Actual De-Escalation Terms","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"PBS coverage noted Trump’s qualified willingness to talk, but the conditional phrasing left unclear what immediate steps would reduce conflict intensity. In high-volatility environments, delayed clarity can extend escalation windows and miscalculation risk. Trump’s wording sounded flexible while remaining operationally non-committal.","rationale":"PBS showed Trump’s qualified talk language without near-term de-escalation clarity.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["eventually willing","de-escalation terms","conditional rhetoric","miscalculation risk","uncertainty"],"metrics_key":"war","source_url":"https://www.pbs.org/newshour/world/white-house-official-irans-new-potential-leadership-suggests-its-open-to-talks-and-trump-says-hes-eventually-willing","source_title":"White House official says potential Iranian leadership could be open to talks","source_publisher":"PBS NewsHour","scores":make_scores("2026-03-03","Foreign Policy","Military Escalation",8,6,8,6,3,3,7,10,"Trump’s conditional talk posture left de-escalation timing and terms opaque.")},
{ "entry_number":1318,"title":"Trump’s Iran Messaging Shifted From ‘Not Happy With Talks’ to Conditional Negotiation Openness in Days","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"Across PBS reporting over late February into early March, Trump moved from hardline dissatisfaction with talks to a more conditional willingness narrative. Rapid message shifts are not automatically policy shifts, but under pressure they can erode confidence in strategic coherence. Partners and adversaries both price that inconsistency.","rationale":"PBS timeline reflected fast Trump messaging swings on Iran diplomacy.","category":"Conspiracy Theories / Disinformation","subcategory":"Systematic Presidential Lying","phase":"White House 2","keywords":["messaging swing","not happy with talks","conditional openness","strategic coherence","policy signal"],"metrics_key":"war","source_url":"https://www.pbs.org/newshour/amp/world/trump-says-hes-not-happy-with-iran-talks-but-will-wait-to-see-what-happens-in-further-rounds","source_title":"Trump says he's not happy with Iran talks but will wait","source_publisher":"PBS NewsHour","scores":make_scores("2026-03-03","Conspiracy Theories / Disinformation","Systematic Presidential Lying",7,5,8,6,4,4,8,10,"Trump’s rapid Iran messaging reversals undermined confidence in stable strategy.")},
{ "entry_number":1319,"title":"Trump’s Crisis Communication Left Negotiation Signals Competing With Escalation Signals","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"AP and PBS reporting together showed a dual message environment: willingness to talk in principle, readiness to escalate in practice, and continued domestic politicization in parallel. Competing signals can be tactically useful, but when overused they reduce predictability for allies and invite adversary testing. Trump’s style pushed toward that instability zone.","rationale":"AP/PBS showed conflicting Trump signals that reduced strategic predictability.","category":"Foreign Policy","subcategory":"Military Escalation","phase":"White House 2","keywords":["conflicting signals","predictability loss","ally uncertainty","adversary testing","crisis communication"],"metrics_key":"war","source_url":"https://apnews.com/article/iran-trump-administration-media-communication-2aeb11fcfef4138c045be71fb7216792","source_title":"White House sends top officials to defend Trump’s Iran policy amid scrutiny","source_publisher":"AP News","scores":make_scores("2026-03-03","Foreign Policy","Military Escalation",8,6,8,6,3,3,8,10,"Trump’s mixed diplomacy-escalation messaging lowered predictability during crisis management.")},
{ "entry_number":1320,"title":"Trump’s Iran Week Ended With Narrative Control Prioritized Over Clear Democratic Accountability","date_start":"2026-03-03","date_end":"2026-03-03","synopsis":"Taken together, AP, Guardian and PBS reporting described a presidency focused on holding narrative dominance while legal process, allied consent and strategic coherence stayed contested. Trump’s core method remained the same under extreme stakes: control the story first, reconcile institutional concerns later. That ordering is precisely what critics call dangerous in a war cycle.","rationale":"Combined reporting showed Trump prioritizing narrative command over institutional clarity.","category":"Authoritarianism","subcategory":"Government Power Abuse","phase":"White House 2","keywords":["narrative control","institutional clarity","allied consent","war accountability","Trump method"],"metrics_key":"governance","source_url":"https://www.theguardian.com/us-news/2026/mar/02/trump-war-iran","source_title":"Trump and the Iran war","source_publisher":"The Guardian","scores":make_scores("2026-03-03","Authoritarianism","Government Power Abuse",8,7,9,7,3,3,8,10,"Trump’s war-week approach prioritized narrative control over institutional accountability.")},
]

entry_cols=["entry_number","title","date_start","date_end","synopsis","rationale","category","subcategory","keywords","age","phase","impressions","reach_estimate","financial_cost_usd","public_reaction","fact_check","fact_check_sources","scores"]
score_cols=["entry_number","insanity","absurdity","danger","authoritarianism","lawlessness","credibility_risk","recency_intensity","impact_scope","rationale_short","rationale_detail"]
source_cols=["entry_number","url","title","publisher","date_published","source_type"]

entry_vals=[]; score_vals=[]; source_vals=[]; keyword_vals=[]
for e in entries:
    m=metrics[e["metrics_key"]]
    e["impressions"]=m["impressions"]; e["reach_estimate"]=m["reach_estimate"]; e["financial_cost_usd"]=m["financial_cost_usd"]; e["public_reaction"]=m["public_reaction"]; e["age"]=calc_age(e["date_start"])
    s=e["scores"]
    entry_vals.append("("+", ".join([
        str(e["entry_number"]),f"'{sql_escape(e['title'])}'",f"'{e['date_start']}'",f"'{e['date_end']}'",f"'{sql_escape(e['synopsis'])}'",f"'{sql_escape(e['rationale'])}'",f"'{sql_escape(e['category'])}'",f"'{sql_escape(e['subcategory'])}'",arr_sql(e["keywords"]),str(e["age"]),f"'{sql_escape(e['phase'])}'",str(e["impressions"]),str(e["reach_estimate"]),str(e["financial_cost_usd"]),json_sql(e["public_reaction"]),"NULL","ARRAY[]::text[]",json_sql(s)
    ])+")")
    score_vals.append("("+", ".join([
        str(e["entry_number"]),str(s["insanity"]),str(s["absurdity"]),str(s["danger"]),str(s["authoritarianism"]),str(s["lawlessness"]),str(s["credibility_risk"]),str(s["recency_intensity"]),str(s["impact_scope"]),f"'{sql_escape(s['rationale_short'])}'",f"'{sql_escape(s['rationale_detail'])}'"
    ])+")")
    source_vals.append("("+", ".join([
        str(e["entry_number"]),f"'{sql_escape(e['source_url'])}'",f"'{sql_escape(e['source_title'])}'",f"'{sql_escape(e['source_publisher'])}'",f"'{e['date_start']}'",f"'news'"
    ])+")")
    for kw in e["keywords"]: keyword_vals.append("("+", ".join([str(e["entry_number"]),f"'{sql_escape(kw)}'"])+")")

sql_entries="INSERT INTO public.trump_entries ("+", ".join(entry_cols)+") VALUES\n"+",\n".join(entry_vals)+"\nON CONFLICT DO NOTHING;"
sql_scores="INSERT INTO public.trump_individual_scores ("+", ".join(score_cols)+") VALUES\n"+",\n".join(score_vals)+"\nON CONFLICT DO NOTHING;"
sql_sources="INSERT INTO public.trump_sources ("+", ".join(source_cols)+") VALUES\n"+",\n".join(source_vals)+";"
sql_keywords="INSERT INTO public.trump_keywords (entry_number, keyword) VALUES\n"+",\n".join(keyword_vals)+"\nON CONFLICT DO NOTHING;"
print(json.dumps([sql_entries,sql_scores,sql_sources,sql_keywords],indent=2))
